/**
 * Auto-generated MQL5 Standard Library stubs for clangd
 * Generated: 2026-01-12T22:06:12.080Z
 * 
 * DO NOT EDIT - This file is auto-generated by mql-stub-generator
 */

#pragma once

#ifdef __clang__

// Forward declarations
class CAccountInfo;
class CDealInfo;
class CHistoryOrderInfo;
class COrderInfo;
class CPositionInfo;
class CSymbolInfo;
class CTerminalInfo;
class CTrade;
class CBmpButton;
class CButton;
class CCheckBox;
class CCheckGroup;
class CComboBox;
class CDateDropList;
class CDatePicker;
class CDialog;
class CAppDialog;
class CEdit;
class CLabel;
class CListView;
class CPanel;
class CPicture;
class CRadioButton;
class CRadioGroup;
class CPoint;
class CSize;
class CRect;
class CScroll;
class CScrollV;
class CScrollH;
class CSpinEdit;
class CWnd;
class CDragWnd;
class CWndClient;
class CWndContainer;
class CWndObj;
class CArray;
class CArrayChar;
class CArrayColor;
class CArrayDatetime;
class CArrayDouble;
class CArrayFloat;
class CArrayInt;
class CArrayLong;
class CArrayObj;
class CArrayShort;
class CArrayString;
class CArrayUChar;
class CArrayUInt;
class CArrayULong;
class CArrayUShort;
class CList;
class CTree;
class CTreeNode;
class CChart;

// Enums
enum ENUM_LOG_LEVELS {
    LOG_LEVEL_NO = 0,
    LOG_LEVEL_ERRORS = 1,
    LOG_LEVEL_ALL = 2
};

enum ENUM_DATE_MODES {
    DATE_MODE_MON,
    DATE_MODE_YEAR
};

enum ENUM_WND_PROP_FLAGS {
    WND_PROP_FLAG_CAN_DBL_CLICK = 1,
    WND_PROP_FLAG_CAN_DRAG = 2,
    WND_PROP_FLAG_CLICKS_BY_PRESS = 4,
    WND_PROP_FLAG_CAN_LOCK = 8,
    WND_PROP_FLAG_READ_ONLY = 16
};

enum ENUM_WND_STATE_FLAGS {
    WND_STATE_FLAG_ENABLE = 1,
    WND_STATE_FLAG_VISIBLE = 2,
    WND_STATE_FLAG_ACTIVE = 4
};

enum ENUM_MOUSE_FLAGS {
    MOUSE_INVALID_FLAGS = -1,
    MOUSE_EMPTY = 0,
    MOUSE_LEFT = 1,
    MOUSE_RIGHT = 2
};

enum ENUM_WND_ALIGN_FLAGS {
    WND_ALIGN_NONE = 0,
    WND_ALIGN_LEFT = 1,
    WND_ALIGN_TOP = 2,
    WND_ALIGN_RIGHT = 4,
    WND_ALIGN_BOTTOM = 8,
    WND_ALIGN_WIDTH = WND_ALIGN_LEFT|WND_ALIGN_RIGHT,
    WND_ALIGN_HEIGHT = WND_ALIGN_TOP|WND_ALIGN_BOTTOM,
    WND_ALIGN_CLIENT = WND_ALIGN_WIDTH|WND_ALIGN_HEIGHT
};

// Classes
class CAccountInfo : public CObject {
public:
    CAccountInfo(void);
    long Login(void) const;
    ENUM_ACCOUNT_TRADE_MODE TradeMode(void) const;
    string TradeModeDescription(void) const;
    long Leverage(void) const;
    ENUM_ACCOUNT_STOPOUT_MODE StopoutMode(void) const;
    string StopoutModeDescription(void) const;
    ENUM_ACCOUNT_MARGIN_MODE MarginMode(void) const;
    string MarginModeDescription(void) const;
    bool TradeAllowed(void) const;
    bool TradeExpert(void) const;
    int LimitOrders(void) const;
    double Balance(void) const;
    double Credit(void) const;
    double Profit(void) const;
    double Equity(void) const;
    double Margin(void) const;
    double FreeMargin(void) const;
    double MarginLevel(void) const;
    double MarginCall(void) const;
    double MarginStopOut(void) const;
    string Name(void) const;
    string Server(void) const;
    string Currency(void) const;
    string Company(void) const;
    long InfoInteger(const ENUM_ACCOUNT_INFO_INTEGER prop_id) const;
    double InfoDouble(const ENUM_ACCOUNT_INFO_DOUBLE prop_id) const;
    string InfoString(const ENUM_ACCOUNT_INFO_STRING prop_id) const;
    double OrderProfitCheck(const string symbol, const ENUM_ORDER_TYPE trade_operation, const double volume, const double price_open, const double price_close) const;
    double MarginCheck(const string symbol, const ENUM_ORDER_TYPE trade_operation, const double volume, const double price) const;
    double FreeMarginCheck(const string symbol, const ENUM_ORDER_TYPE trade_operation, const double volume, const double price) const;
    double MaxLotCheck(const string symbol, const ENUM_ORDER_TYPE trade_operation, const double price, const double percent = 100) const;
};

class CDealInfo : public CObject {
public:
    CDealInfo(void);
    long Order(void) const;
    datetime Time(void) const;
    ulong TimeMsc(void) const;
    ENUM_DEAL_TYPE DealType(void) const;
    string TypeDescription(void) const;
    ENUM_DEAL_ENTRY Entry(void) const;
    string EntryDescription(void) const;
    long Magic(void) const;
    long PositionId(void) const;
    double Volume(void) const;
    double Price(void) const;
    double Commission(void) const;
    double Swap(void) const;
    double Profit(void) const;
    string Symbol(void) const;
    string Comment(void) const;
    string ExternalId(void) const;
    bool InfoInteger(ENUM_DEAL_PROPERTY_INTEGER prop_id, long & var) const;
    bool InfoDouble(ENUM_DEAL_PROPERTY_DOUBLE prop_id, double & var) const;
    bool InfoString(ENUM_DEAL_PROPERTY_STRING prop_id, string & var) const;
    string FormatAction(string & str, const uint action) const;
    string FormatEntry(string & str, const uint entry) const;
    string FormatDeal(string & str) const;
    bool SelectByIndex(const int index);
protected:
    ulong m_ticket;
};

class CHistoryOrderInfo : public CObject {
public:
    CHistoryOrderInfo(void);
    datetime TimeSetup(void) const;
    ulong TimeSetupMsc(void) const;
    datetime TimeDone(void) const;
    ulong TimeDoneMsc(void) const;
    ENUM_ORDER_TYPE OrderType(void) const;
    string TypeDescription(void) const;
    ENUM_ORDER_STATE State(void) const;
    string StateDescription(void) const;
    datetime TimeExpiration(void) const;
    ENUM_ORDER_TYPE_FILLING TypeFilling(void) const;
    string TypeFillingDescription(void) const;
    ENUM_ORDER_TYPE_TIME TypeTime(void) const;
    string TypeTimeDescription(void) const;
    long Magic(void) const;
    long PositionId(void) const;
    long PositionById(void) const;
    double VolumeInitial(void) const;
    double VolumeCurrent(void) const;
    double PriceOpen(void) const;
    double StopLoss(void) const;
    double TakeProfit(void) const;
    double PriceCurrent(void) const;
    double PriceStopLimit(void) const;
    string Symbol(void) const;
    string Comment(void) const;
    string ExternalId(void) const;
    bool InfoInteger(const ENUM_ORDER_PROPERTY_INTEGER prop_id, long & var) const;
    bool InfoDouble(const ENUM_ORDER_PROPERTY_DOUBLE prop_id, double & var) const;
    bool InfoString(const ENUM_ORDER_PROPERTY_STRING prop_id, string & var) const;
    string FormatType(string & str, const uint type) const;
    string FormatStatus(string & str, const uint status) const;
    string FormatTypeFilling(string & str, const uint type) const;
    string FormatTypeTime(string & str, const uint type) const;
    string FormatOrder(string & str) const;
    string FormatPrice(string & str, const double price_order, const double price_trigger, const uint digits) const;
    bool SelectByIndex(const int index);
protected:
    ulong m_ticket;
};

class COrderInfo : public CObject {
public:
    COrderInfo(void);
    datetime TimeSetup(void) const;
    ulong TimeSetupMsc(void) const;
    datetime TimeDone(void) const;
    ulong TimeDoneMsc(void) const;
    ENUM_ORDER_TYPE OrderType(void) const;
    string TypeDescription(void) const;
    ENUM_ORDER_STATE State(void) const;
    string StateDescription(void) const;
    datetime TimeExpiration(void) const;
    ENUM_ORDER_TYPE_FILLING TypeFilling(void) const;
    string TypeFillingDescription(void) const;
    ENUM_ORDER_TYPE_TIME TypeTime(void) const;
    string TypeTimeDescription(void) const;
    long Magic(void) const;
    long PositionId(void) const;
    long PositionById(void) const;
    double VolumeInitial(void) const;
    double VolumeCurrent(void) const;
    double PriceOpen(void) const;
    double StopLoss(void) const;
    double TakeProfit(void) const;
    double PriceCurrent(void) const;
    double PriceStopLimit(void) const;
    string Symbol(void) const;
    string Comment(void) const;
    string ExternalId(void) const;
    bool InfoInteger(const ENUM_ORDER_PROPERTY_INTEGER prop_id, long & var) const;
    bool InfoDouble(const ENUM_ORDER_PROPERTY_DOUBLE prop_id, double & var) const;
    bool InfoString(const ENUM_ORDER_PROPERTY_STRING prop_id, string & var) const;
    string FormatType(string & str, const uint type) const;
    string FormatStatus(string & str, const uint status) const;
    string FormatTypeFilling(string & str, const uint type) const;
    string FormatTypeTime(string & str, const uint type) const;
    string FormatOrder(string & str) const;
    string FormatPrice(string & str, const double price_order, const double price_trigger, const uint digits) const;
    bool Select(void);
    bool Select(const ulong ticket);
    bool SelectByIndex(const int index);
    void StoreState(void);
    bool CheckState(void);
protected:
    ulong m_ticket;
    ENUM_ORDER_TYPE m_type;
    ENUM_ORDER_STATE m_state;
    datetime m_expiration;
    double m_volume_curr;
    double m_price_open;
    double m_stop_loss;
    double m_take_profit;
};

class CPositionInfo : public CObject {
public:
    CPositionInfo(void);
    ulong Ticket(void) const;
    datetime Time(void) const;
    ulong TimeMsc(void) const;
    datetime TimeUpdate(void) const;
    ulong TimeUpdateMsc(void) const;
    ENUM_POSITION_TYPE PositionType(void) const;
    string TypeDescription(void) const;
    long Magic(void) const;
    long Identifier(void) const;
    double Volume(void) const;
    double PriceOpen(void) const;
    double StopLoss(void) const;
    double TakeProfit(void) const;
    double PriceCurrent(void) const;
    double Commission(void) const;
    double Swap(void) const;
    double Profit(void) const;
    string Symbol(void) const;
    string Comment(void) const;
    bool InfoInteger(const ENUM_POSITION_PROPERTY_INTEGER prop_id, long & var) const;
    bool InfoDouble(const ENUM_POSITION_PROPERTY_DOUBLE prop_id, double & var) const;
    bool InfoString(const ENUM_POSITION_PROPERTY_STRING prop_id, string & var) const;
    string FormatType(string & str, const uint type) const;
    string FormatPosition(string & str) const;
    bool Select(const string symbol);
    bool SelectByMagic(const string symbol, const ulong magic);
    bool SelectByTicket(const ulong ticket);
    bool SelectByIndex(const int index);
    void StoreState(void);
    bool CheckState(void);
protected:
    ENUM_POSITION_TYPE m_type;
    double m_volume;
    double m_price;
    double m_stop_loss;
    double m_take_profit;
};

class CSymbolInfo : public CObject {
public:
    CSymbolInfo(void);
    bool Name(const string name);
    bool Refresh(void);
    bool RefreshRates(void);
    bool Select(void) const;
    bool Select(const bool select);
    bool IsSynchronized(void) const;
    ulong VolumeHigh(void) const;
    ulong VolumeLow(void) const;
    int Spread(void) const;
    bool SpreadFloat(void) const;
    int TicksBookDepth(void) const;
    int StopsLevel(void) const;
    int FreezeLevel(void) const;
    double BidHigh(void) const;
    double BidLow(void) const;
    double AskHigh(void) const;
    double AskLow(void) const;
    double LastHigh(void) const;
    double LastLow(void) const;
    string TradeCalcModeDescription(void) const;
    string TradeModeDescription(void) const;
    string TradeExecutionDescription(void) const;
    string SwapModeDescription(void) const;
    string SwapRollover3daysDescription(void) const;
    datetime StartTime(void) const;
    datetime ExpirationTime(void) const;
    string CurrencyBase(void) const;
    string CurrencyProfit(void) const;
    string CurrencyMargin(void) const;
    string Bank(void) const;
    string Description(void) const;
    string Path(void) const;
    long SessionDeals(void) const;
    long SessionBuyOrders(void) const;
    long SessionSellOrders(void) const;
    double SessionTurnover(void) const;
    double SessionInterest(void) const;
    double SessionBuyOrdersVolume(void) const;
    double SessionSellOrdersVolume(void) const;
    double SessionOpen(void) const;
    double SessionClose(void) const;
    double SessionAW(void) const;
    double SessionPriceSettlement(void) const;
    double SessionPriceLimitMin(void) const;
    double SessionPriceLimitMax(void) const;
    bool InfoInteger(const ENUM_SYMBOL_INFO_INTEGER prop_id, long& var) const;
    bool InfoDouble(const ENUM_SYMBOL_INFO_DOUBLE prop_id, double& var) const;
    bool InfoString(const ENUM_SYMBOL_INFO_STRING prop_id, string& var) const;
    bool InfoMarginRate(const ENUM_ORDER_TYPE order_type, double& initial_margin_rate, double& maintenance_margin_rate) const;
    double NormalizePrice(const double price) const;
    bool CheckMarketWatch(void);
protected:
    string m_name;
    MqlTick m_tick;
    double m_point;
    double m_tick_value;
    double m_tick_value_profit;
    double m_tick_value_loss;
    double m_tick_size;
    double m_contract_size;
    double m_lots_min;
    double m_lots_max;
    double m_lots_step;
    double m_lots_limit;
    double m_swap_long;
    double m_swap_short;
    int m_digits;
    int m_order_mode;
    ENUM_SYMBOL_TRADE_EXECUTION m_trade_execution;
    ENUM_SYMBOL_CALC_MODE m_trade_calcmode;
    ENUM_SYMBOL_TRADE_MODE m_trade_mode;
    ENUM_SYMBOL_SWAP_MODE m_swap_mode;
    ENUM_DAY_OF_WEEK m_swap3;
    double m_margin_initial;
    double m_margin_maintenance;
    bool m_margin_hedged_use_leg;
    double m_margin_hedged;
    int m_trade_time_flags;
    int m_trade_fill_flags;
};

class CTerminalInfo : public CObject {
public:
    CTerminalInfo(void);
    int Build(void) const;
    bool IsConnected(void) const;
    bool IsDLLsAllowed(void) const;
    bool IsTradeAllowed(void) const;
    bool IsEmailEnabled(void) const;
    bool IsFtpEnabled(void) const;
    int MaxBars(void) const;
    int CodePage(void) const;
    int CPUCores(void) const;
    int MemoryPhysical(void) const;
    int MemoryTotal(void) const;
    int MemoryAvailable(void) const;
    int MemoryUsed(void) const;
    bool IsX64(void) const;
    int OpenCLSupport(void) const;
    int DiskSpace(void) const;
    string Language(void) const;
    string Name(void) const;
    string Company(void) const;
    string Path(void) const;
    string DataPath(void) const;
    string CommonDataPath(void) const;
    long InfoInteger(const ENUM_TERMINAL_INFO_INTEGER prop_id) const;
    string InfoString(const ENUM_TERMINAL_INFO_STRING prop_id) const;
};

class CTrade : public CObject {
public:
    CTrade(void);
    void Request(MqlTradeRequest & request) const;
    string RequestActionDescription(void) const;
    string RequestTypeDescription(void) const;
    string RequestTypeFillingDescription(void) const;
    string RequestTypeTimeDescription(void) const;
    void Result(MqlTradeResult & result) const;
    string ResultRetcodeDescription(void) const;
    void CheckResult(MqlTradeCheckResult & check_result) const;
    string CheckResultRetcodeDescription(void) const;
    bool SetTypeFillingBySymbol(const string symbol);
    bool PositionOpen(const string symbol, const ENUM_ORDER_TYPE order_type, const double volume, const double price, const double sl, const double tp, const string comment = "");
    bool PositionModify(const string symbol, const double sl, const double tp);
    bool PositionModify(const ulong ticket, const double sl, const double tp);
    bool PositionClose(const string symbol, const ulong deviation = ULONG_MAX);
    bool PositionClose(const ulong ticket, const ulong deviation = ULONG_MAX);
    bool PositionCloseBy(const ulong ticket, const ulong ticket_by);
    bool PositionClosePartial(const string symbol, const double volume, const ulong deviation = ULONG_MAX);
    bool PositionClosePartial(const ulong ticket, const double volume, const ulong deviation = ULONG_MAX);
    bool OrderOpen(const string symbol, const ENUM_ORDER_TYPE order_type, const double volume, const double limit_price, const double price, const double sl, const double tp, ENUM_ORDER_TYPE_TIME type_time = ORDER_TIME_GTC, const datetime expiration = 0, const string comment = "");
    bool OrderModify(const ulong ticket, const double price, const double sl, const double tp, const ENUM_ORDER_TYPE_TIME type_time, const datetime expiration, const double stoplimit = 0.0);
    bool OrderDelete(const ulong ticket);
    bool Buy(const double volume, const string symbol = NULL, double price = 0.0, const double sl = 0.0, const double tp = 0.0, const string comment = "");
    bool Sell(const double volume, const string symbol = NULL, double price = 0.0, const double sl = 0.0, const double tp = 0.0, const string comment = "");
    bool BuyLimit(const double volume, const double price, const string symbol = NULL, const double sl = 0.0, const double tp = 0.0, const ENUM_ORDER_TYPE_TIME type_time = ORDER_TIME_GTC, const datetime expiration = 0, const string comment = "");
    bool BuyStop(const double volume, const double price, const string symbol = NULL, const double sl = 0.0, const double tp = 0.0, const ENUM_ORDER_TYPE_TIME type_time = ORDER_TIME_GTC, const datetime expiration = 0, const string comment = "");
    bool SellLimit(const double volume, const double price, const string symbol = NULL, const double sl = 0.0, const double tp = 0.0, const ENUM_ORDER_TYPE_TIME type_time = ORDER_TIME_GTC, const datetime expiration = 0, const string comment = "");
    bool SellStop(const double volume, const double price, const string symbol = NULL, const double sl = 0.0, const double tp = 0.0, const ENUM_ORDER_TYPE_TIME type_time = ORDER_TIME_GTC, const datetime expiration = 0, const string comment = "");
    virtual double CheckVolume(const string symbol, double volume, double price, ENUM_ORDER_TYPE order_type);
    virtual bool OrderCheck(const MqlTradeRequest & request, MqlTradeCheckResult & check_result);
    virtual bool OrderSend(const MqlTradeRequest & request, MqlTradeResult & result);
    void PrintRequest(void) const;
    void PrintResult(void) const;
    string FormatPositionType(string & str, const uint type) const;
    string FormatOrderType(string & str, const uint type) const;
    string FormatOrderStatus(string & str, const uint status) const;
    string FormatOrderTypeFilling(string & str, const uint type) const;
    string FormatOrderTypeTime(string & str, const uint type) const;
    string FormatOrderPrice(string & str, const double price_order, const double price_trigger, const uint digits) const;
    string FormatRequest(string & str, const MqlTradeRequest & request) const;
    string FormatRequestResult(string & str, const MqlTradeRequest & request, const MqlTradeResult & result) const;
protected:
    MqlTradeRequest m_request;
    MqlTradeResult m_result;
    MqlTradeCheckResult m_check_result;
    bool m_async_mode;
    ulong m_magic;
    ulong m_deviation;
    ENUM_ORDER_TYPE_FILLING m_type_filling;
    ENUM_ACCOUNT_MARGIN_MODE m_margin_mode;
    ENUM_LOG_LEVELS m_log_level;
    bool FillingCheck(const string symbol);
    bool ExpirationCheck(const string symbol);
    bool OrderTypeCheck(const string symbol);
    void ClearStructures(void);
    bool IsStopped(const string function);
    bool SelectPosition(const string symbol);
};

class CWnd : public CObject {
public:
    CWnd(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual void Destroy(const int reason = 0);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    virtual bool OnMouseEvent(const int x, const int y, const int flags);
    virtual CWnd* ControlFind(const long id);
    virtual bool Width(const int w);
    virtual bool Height(const int h);
    virtual bool Size(const int w, const int h);
    virtual bool Size(const CSize & size);
    virtual bool Move(const int x, const int y);
    virtual bool Move(const CPoint & point);
    virtual bool Shift(const int dx, const int dy);
    bool Contains(CWnd * control) const;
    void Alignment(const int flags, const int left, const int top, const int right, const int bottom);
    virtual bool Align(const CRect & rect);
    virtual long Id(const long id);
    virtual bool Enable(void);
    virtual bool Disable(void);
    virtual bool Visible(const bool flag);
    virtual bool Show(void);
    virtual bool Hide(void);
    virtual bool Activate(void);
    virtual bool Deactivate(void);
    bool MouseFocusKill(const long id = CONTROLS_INVALID_ID);
    bool BringToTop(void);
protected:
    long m_chart_id;
    int m_subwin;
    string m_name;
    CRect m_rect;
    long m_id;
    int m_state_flags;
    int m_prop_flags;
    int m_align_flags;
    int m_align_left;
    int m_align_top;
    int m_align_right;
    int m_align_bottom;
    int m_mouse_x;
    int m_mouse_y;
    int m_mouse_flags;
    uint m_last_click;
    virtual bool OnClick(void);
    virtual bool OnDblClick(void);
    virtual bool OnMouseDown(void);
    virtual bool OnMouseUp(void);
    virtual bool OnDragStart(void);
    virtual bool OnDragProcess(const int x, const int y);
    virtual bool OnDragEnd(void);
    virtual bool DragObjectDestroy(void);
};

class CWndObj : public CWnd {
public:
    CWndObj(void);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    bool Text(const string value);
    bool Color(const color value);
    bool ColorBackground(const color value);
    bool ColorBorder(const color value);
    bool Font(const string value);
    bool FontSize(const int value);
    bool ZOrder(const long value);
protected:
    string m_text;
    color m_color;
    color m_color_background;
    color m_color_border;
    string m_font;
    int m_font_size;
    long m_zorder;
    virtual bool OnObjectCreate(void);
    virtual bool OnObjectChange(void);
    virtual bool OnObjectDelete(void);
    virtual bool OnObjectDrag(void);
    virtual bool OnChange(void);
};

class CBmpButton : public CWndObj {
public:
    CBmpButton(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    bool Border(const int value);
    bool BmpNames(const string off = "", const string on = "");
    bool BmpOffName(const string name);
    bool BmpOnName(const string name);
    bool BmpPassiveName(const string name);
    bool BmpActiveName(const string name);
    void Locking(const bool locking);
protected:
    virtual bool OnCreate(void);
    virtual bool OnShow(void);
    virtual bool OnHide(void);
    virtual bool OnMove(void);
    virtual bool OnChange(void);
    virtual bool OnActivate(void);
    virtual bool OnDeactivate(void);
    virtual bool OnMouseDown(void);
    virtual bool OnMouseUp(void);
};

class CButton : public CWndObj {
public:
    CButton(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    void Locking(const bool flag);
protected:
    virtual bool OnCreate(void);
    virtual bool OnShow(void);
    virtual bool OnHide(void);
    virtual bool OnMove(void);
    virtual bool OnResize(void);
    virtual bool OnMouseDown(void);
    virtual bool OnMouseUp(void);
};

class CWndContainer : public CWnd {
public:
    CWndContainer(void);
    virtual void Destroy(const int reason = 0);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    virtual bool OnMouseEvent(const int x, const int y, const int flags);
    virtual CWnd* ControlFind(const long id);
    virtual bool MouseFocusKill(const long id = -1);
    bool Add(CWnd * control);
    bool Add(CWnd & control);
    bool Delete(CWnd * control);
    bool Delete(CWnd & control);
    virtual bool Move(const int x, const int y);
    virtual bool Move(const CPoint & point);
    virtual bool Shift(const int dx, const int dy);
    virtual long Id(const long id);
    virtual bool Enable(void);
    virtual bool Disable(void);
    virtual bool Show(void);
    virtual bool Hide(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
protected:
    virtual bool OnResize(void);
    virtual bool OnActivate(void);
    virtual bool OnDeactivate(void);
};

class CCheckBox : public CWndContainer {
public:
    CCheckBox(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
protected:
    virtual bool CreateButton(void);
    virtual bool CreateLabel(void);
    virtual bool OnClickButton(void);
    virtual bool OnClickLabel(void);
};

class CWndClient : public CWndContainer {
public:
    CWndClient(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    virtual bool VScrolled(const bool flag);
    virtual bool HScrolled(const bool flag);
    virtual long Id(const long id);
    virtual bool Show(void);
protected:
    bool m_v_scrolled;
    bool m_h_scrolled;
    CPanel m_background;
    CScrollV m_scroll_v;
    CScrollH m_scroll_h;
    virtual bool CreateBack(void);
    virtual bool CreateScrollV(void);
    virtual bool CreateScrollH(void);
    virtual bool OnResize(void);
    virtual bool Rebound(const CRect & rect);
};

class CCheckGroup : public CWndClient {
public:
    CCheckGroup(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual void Destroy(const int reason = 0);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    virtual bool AddItem(const string item, const long value = 0);
    long Value(void) const;
    bool Value(const long value);
    int Check(const int idx) const;
    bool Check(const int idx, const int value);
    virtual bool Show(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
protected:
    bool CreateButton(int index);
    virtual bool OnVScrollShow(void);
    virtual bool OnVScrollHide(void);
    virtual bool OnScrollLineDown(void);
    virtual bool OnScrollLineUp(void);
    virtual bool OnChangeItem(const int row_index);
    bool Redraw(void);
    bool RowState(const int index, const bool select);
};

class CComboBox : public CWndContainer {
public:
    CComboBox(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    bool AddItem(const string item, const long value = 0);
    bool Select(const int index);
    bool SelectByText(const string text);
    bool SelectByValue(const long value);
    virtual bool Show(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
protected:
    virtual bool CreateEdit(void);
    virtual bool CreateButton(void);
    virtual bool CreateList(void);
    virtual bool OnClickEdit(void);
    virtual bool OnClickButton(void);
    virtual bool OnChangeList(void);
    bool ListShow(void);
    bool ListHide(void);
    void CheckListHide(const int id, int x, int y);
};

class CDateDropList : public CWndContainer {
public:
    CDateDropList(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    virtual bool Show(void);
protected:
    virtual bool OnClick(void);
    virtual bool CreateButtons(void);
    virtual bool CreateList(void);
    void DrawCanvas(void);
    void DrawClickRect(const int idx, int x, int y, string text, const uint clr, uint alignment = 0);
    virtual bool OnClickDec(void);
    virtual bool OnClickInc(void);
    virtual bool OnClickList(void);
};

class CDatePicker : public CWndContainer {
public:
    CDatePicker(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    virtual bool Show(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
protected:
    virtual bool CreateEdit(void);
    virtual bool CreateButton(void);
    virtual bool CreateList(void);
    virtual bool OnClickEdit(void);
    virtual bool OnClickButton(void);
    virtual bool OnChangeList(void);
    bool ListShow(void);
    bool ListHide(void);
    void CheckListHide(const int id, int x, int y);
};

class CDialog : public CWndContainer {
public:
    CDialog(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    bool Add(CWnd * control);
    bool Add(CWnd & control);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
protected:
    bool m_panel_flag;
    bool m_minimized;
    CRect m_min_rect;
    CRect m_norm_rect;
    virtual bool CreateWhiteBorder(void);
    virtual bool CreateBackground(void);
    virtual bool CreateCaption(void);
    virtual bool CreateButtonClose(void);
    virtual bool CreateClientArea(void);
    virtual void OnClickCaption(void);
    virtual void OnClickButtonClose(void);
    virtual bool OnDialogDragStart(void);
    virtual bool OnDialogDragProcess(void);
    virtual bool OnDialogDragEnd(void);
};

class CAppDialog : public CDialog {
public:
    CAppDialog(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual void Destroy(const int reason = REASON_PROGRAM);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    bool Run(void);
    void ChartEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    void IniFileSave(void);
    void IniFileLoad(void);
    virtual string IniFileName(void) const;
    virtual bool Load(const int file_handle);
    virtual bool Save(const int file_handle);
protected:
    CChart m_chart;
    virtual bool CreateButtonMinMax(void);
    virtual void OnClickButtonClose(void);
    virtual void OnClickButtonMinMax(void);
    virtual void OnAnotherApplicationClose(const long & lparam, const double & dparam, const string & sparam);
    virtual bool Rebound(const CRect & rect);
    virtual void Minimize(void);
    virtual void Maximize(void);
    string CreateInstanceId(void);
    void SubwinOff(void);
};

class CEdit : public CWndObj {
public:
    CEdit(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    bool ReadOnly(const bool flag);
    bool TextAlign(const ENUM_ALIGN_MODE align);
protected:
    virtual bool OnObjectEndEdit(void);
    virtual bool OnCreate(void);
    virtual bool OnShow(void);
    virtual bool OnHide(void);
    virtual bool OnMove(void);
    virtual bool OnResize(void);
    virtual bool OnChange(void);
    virtual bool OnClick(void);
};

class CLabel : public CWndObj {
public:
    CLabel(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
protected:
    virtual bool OnCreate(void);
    virtual bool OnShow(void);
    virtual bool OnHide(void);
    virtual bool OnMove(void);
};

class CListView : public CWndClient {
public:
    CListView(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual void Destroy(const int reason = 0);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    bool TotalView(const int value);
    virtual bool AddItem(const string item, const long value = 0);
    virtual bool ItemAdd(const string item, const long value = 0);
    virtual bool ItemInsert(const int index, const string item, const long value = 0);
    virtual bool ItemUpdate(const int index, const string item, const long value = 0);
    virtual bool ItemDelete(const int index);
    virtual bool ItemsClear(void);
    bool Select(const int index);
    bool SelectByText(const string text);
    bool SelectByValue(const long value);
    virtual bool Show(void);
protected:
    bool CreateRow(const int index);
    virtual bool OnResize(void);
    virtual bool OnVScrollShow(void);
    virtual bool OnVScrollHide(void);
    virtual bool OnScrollLineDown(void);
    virtual bool OnScrollLineUp(void);
    virtual bool OnItemClick(const int index);
    bool Redraw(void);
    bool RowState(const int index, const bool select);
    bool CheckView(void);
};

class CPanel : public CWndObj {
public:
    CPanel(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    bool BorderType(const ENUM_BORDER_TYPE type);
protected:
    virtual bool OnCreate(void);
    virtual bool OnShow(void);
    virtual bool OnHide(void);
    virtual bool OnMove(void);
    virtual bool OnResize(void);
    virtual bool OnChange(void);
};

class CPicture : public CWndObj {
public:
    CPicture(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    bool Border(const int value);
    bool BmpName(const string name);
protected:
    virtual bool OnCreate(void);
    virtual bool OnShow(void);
    virtual bool OnHide(void);
    virtual bool OnMove(void);
    virtual bool OnChange(void);
};

class CRadioButton : public CWndContainer {
public:
    CRadioButton(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
protected:
    virtual bool CreateButton(void);
    virtual bool CreateLabel(void);
    virtual bool OnClickButton(void);
    virtual bool OnClickLabel(void);
};

class CRadioGroup : public CWndClient {
public:
    CRadioGroup(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual void Destroy(const int reason = 0);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    virtual bool AddItem(const string item, const long value = 0);
    bool Value(const long value);
    bool ValueCheck(long value) const;
    virtual bool Show(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
protected:
    bool CreateButton(const int index);
    virtual bool OnVScrollShow(void);
    virtual bool OnVScrollHide(void);
    virtual bool OnScrollLineDown(void);
    virtual bool OnScrollLineUp(void);
    virtual bool OnChangeItem(const int row_index);
    bool Redraw(void);
    bool RowState(const int index, const bool select);
    void Select(const int index);
};

struct CPoint {
public:
    int x;
    int y;
};

struct CSize {
public:
    int cx;
    int cy;
};

struct CRect {
public:
    int left;
    int top;
    int right;
    int bottom;
    CPoint LeftTop(void) const;
    void LeftTop(const int x, const int y);
    void LeftTop(const CPoint& point);
    CPoint RightBottom(void) const;
    void RightBottom(const int x, const int y);
    void RightBottom(const CPoint& point);
    CPoint CenterPoint(void) const;
    CSize Size(void) const;
    void Size(const int cx, const int cy);
    void Size(const CSize& size);
    void SetBound(const int l, const int t, const int r, const int b);
    void SetBound(const CRect& rect);
    void SetBound(const CPoint& point, const CSize& size);
    void SetBound(const CPoint& left_top, const CPoint& right_bottom);
    void Move(const int x, const int y);
    void Move(const CPoint& point);
    void Shift(const int dx, const int dy);
    void Shift(const CPoint& point);
    void Shift(const CSize& size);
    bool Contains(const int x, const int y) const;
    bool Contains(const CPoint& point) const;
    void Normalize(void);
};

class CScroll : public CWndContainer {
public:
    CScroll(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    void MinPos(const int value);
    void MaxPos(const int value);
    bool CurrPos(int value);
protected:
    CPanel m_back;
    CBmpButton m_inc;
    CBmpButton m_dec;
    CBmpButton m_thumb;
    int m_min_pos;
    int m_max_pos;
    int m_curr_pos;
    virtual bool CreateBack(void);
    virtual bool OnClickInc(void);
    virtual bool OnClickDec(void);
    virtual bool OnShow(void);
    virtual bool OnHide(void);
};

class CScrollV : public CScroll {
public:
    CScrollV(void);
protected:
    virtual bool CreateInc(void);
    virtual bool CreateDec(void);
    virtual bool CreateThumb(void);
    virtual bool OnResize(void);
    virtual bool OnChangePos(void);
    virtual bool OnThumbDragStart(void);
    virtual bool OnThumbDragProcess(void);
    virtual bool OnThumbDragEnd(void);
    virtual int CalcPos(const int coord);
};

class CScrollH : public CScroll {
public:
    CScrollH(void);
protected:
    virtual bool CreateInc(void);
    virtual bool CreateDec(void);
    virtual bool CreateThumb(void);
    virtual bool OnResize(void);
    virtual bool OnChangePos(void);
    virtual bool OnThumbDragStart(void);
    virtual bool OnThumbDragProcess(void);
    virtual bool OnThumbDragEnd(void);
    virtual int CalcPos(const int coord);
};

class CSpinEdit : public CWndContainer {
public:
    CSpinEdit(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    void MinValue(const int value);
    void MaxValue(const int value);
    bool Value(int value);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
protected:
    virtual bool CreateEdit(void);
    virtual bool CreateInc(void);
    virtual bool CreateDec(void);
    virtual bool OnClickInc(void);
    virtual bool OnClickDec(void);
    virtual bool OnChangeValue(void);
};

class CDragWnd : public CWnd {
public:
    CDragWnd(void);
    void Limits(const int l, const int t, const int r, const int b);
protected:
    int m_limit_left;
    int m_limit_top;
    int m_limit_right;
    int m_limit_bottom;
    virtual bool OnDragProcess(const int x, const int y);
};

class CArray : public CObject {
public:
    CArray(void);
    bool Step(const int step);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    void Sort(const int mode = 0);
protected:
    int m_step_resize;
    int m_data_total;
    int m_data_max;
    int m_sort_mode;
};

class CArrayChar : public CArray {
public:
    CArrayChar(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(const char element);
    bool AddArray(const char & src);
    bool AddArray(const CArrayChar * src);
    bool Insert(const char element, const int pos);
    bool InsertArray(const char & src, const int pos);
    bool InsertArray(const CArrayChar * src, const int pos);
    bool AssignArray(const char & src);
    bool AssignArray(const CArrayChar * src);
    char At(const int index) const;
    bool Update(const int index, const char element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    bool CompareArray(const char & array) const;
    bool CompareArray(const CArrayChar * array) const;
    bool InsertSort(const char element);
    int Search(const char element) const;
    int SearchGreat(const char element) const;
    int SearchLess(const char element) const;
    int SearchGreatOrEqual(const char element) const;
    int SearchLessOrEqual(const char element) const;
    int SearchFirst(const char element) const;
    int SearchLast(const char element) const;
    int SearchLinear(const char element) const;
protected:
    char m_data;
    virtual void QuickSort(int beg, int end, const int mode = 0);
    int QuickSearch(const char element) const;
    int MemMove(const int dest, const int src, int count);
};

class CArrayColor : public CArray {
public:
    CArrayColor(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(const color element);
    bool AddArray(const color & src);
    bool AddArray(const CArrayColor * src);
    bool Insert(const color element, const int pos);
    bool InsertArray(const color & src, const int pos);
    bool InsertArray(const CArrayColor * src, const int pos);
    bool AssignArray(const color & src);
    bool AssignArray(const CArrayColor * src);
    color At(const int index) const;
    bool Update(const int index, const color element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    bool CompareArray(const color & array) const;
    bool CompareArray(const CArrayColor * array) const;
    bool InsertSort(const color element);
    int Search(const color element) const;
    int SearchGreat(const color element) const;
    int SearchLess(const color element) const;
    int SearchGreatOrEqual(const color element) const;
    int SearchLessOrEqual(const color element) const;
    int SearchFirst(const color element) const;
    int SearchLast(const color element) const;
    int SearchLinear(const color element) const;
protected:
    color m_data;
    virtual void QuickSort(int beg, int end, const int mode = 0);
    int QuickSearch(const color element) const;
    int MemMove(const int dest, const int src, int count);
};

class CArrayDatetime : public CArray {
public:
    CArrayDatetime(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(const datetime element);
    bool AddArray(const datetime & src);
    bool AddArray(const CArrayDatetime * src);
    bool Insert(const datetime element, const int pos);
    bool InsertArray(const datetime & src, const int pos);
    bool InsertArray(const CArrayDatetime * src, const int pos);
    bool AssignArray(const datetime & src);
    bool AssignArray(const CArrayDatetime * src);
    datetime At(const int index) const;
    bool Update(const int index, const datetime element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    bool CompareArray(const datetime & array) const;
    bool CompareArray(const CArrayDatetime * array) const;
    bool InsertSort(const datetime element);
    int Search(const datetime element) const;
    int SearchGreat(const datetime element) const;
    int SearchLess(const datetime element) const;
    int SearchGreatOrEqual(const datetime element) const;
    int SearchLessOrEqual(const datetime element) const;
    int SearchFirst(const datetime element) const;
    int SearchLast(const datetime element) const;
    int SearchLinear(const datetime element) const;
protected:
    datetime m_data;
    virtual void QuickSort(int beg, int end, const int mode = 0);
    int QuickSearch(const datetime element) const;
    int MemMove(const int dest, const int src, int count);
};

class CArrayDouble : public CArray {
public:
    CArrayDouble(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(const double element);
    bool AddArray(const double & src);
    bool AddArray(const CArrayDouble * src);
    bool Insert(const double element, const int pos);
    bool InsertArray(const double & src, const int pos);
    bool InsertArray(const CArrayDouble * src, const int pos);
    bool AssignArray(const double & src);
    bool AssignArray(const CArrayDouble * src);
    double At(const int index) const;
    bool Update(const int index, const double element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    bool CompareArray(const double & array) const;
    bool CompareArray(const CArrayDouble * array) const;
    bool InsertSort(const double element);
    int Search(const double element) const;
    int SearchGreat(const double element) const;
    int SearchLess(const double element) const;
    int SearchGreatOrEqual(const double element) const;
    int SearchLessOrEqual(const double element) const;
    int SearchFirst(const double element) const;
    int SearchLast(const double element) const;
    int SearchLinear(const double element) const;
protected:
    double m_data;
    double m_delta;
    virtual void QuickSort(int beg, int end, const int mode = 0);
    int QuickSearch(const double element) const;
    int MemMove(const int dest, const int src, int count);
};

class CArrayFloat : public CArray {
public:
    CArrayFloat(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(const float element);
    bool AddArray(const float & src);
    bool AddArray(const CArrayFloat * src);
    bool Insert(const float element, const int pos);
    bool InsertArray(const float & src, const int pos);
    bool InsertArray(const CArrayFloat * src, const int pos);
    bool AssignArray(const float & src);
    bool AssignArray(const CArrayFloat * src);
    float At(const int index) const;
    bool Update(const int index, const float element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    bool CompareArray(const float & array) const;
    bool CompareArray(const CArrayFloat * array) const;
    bool InsertSort(const float element);
    int Search(const float element) const;
    int SearchGreat(const float element) const;
    int SearchLess(const float element) const;
    int SearchGreatOrEqual(const float element) const;
    int SearchLessOrEqual(const float element) const;
    int SearchFirst(const float element) const;
    int SearchLast(const float element) const;
    int SearchLinear(const float element) const;
protected:
    float m_data;
    float m_delta;
    virtual void QuickSort(int beg, int end, const int mode = 0);
    int QuickSearch(const float element) const;
    int MemMove(const int dest, const int src, int count);
};

class CArrayInt : public CArray {
public:
    CArrayInt(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(const int element);
    bool AddArray(const int & src);
    bool AddArray(const CArrayInt * src);
    bool Insert(const int element, const int pos);
    bool InsertArray(const int & src, const int pos);
    bool InsertArray(const CArrayInt * src, const int pos);
    bool AssignArray(const int & src);
    bool AssignArray(const CArrayInt * src);
    int At(const int index) const;
    bool Update(const int index, const int element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    bool CompareArray(const int & array) const;
    bool CompareArray(const CArrayInt * array) const;
    bool InsertSort(const int element);
    int Search(const int element) const;
    int SearchGreat(const int element) const;
    int SearchLess(const int element) const;
    int SearchGreatOrEqual(const int element) const;
    int SearchLessOrEqual(const int element) const;
    int SearchFirst(const int element) const;
    int SearchLast(const int element) const;
    int SearchLinear(const int element) const;
protected:
    int m_data;
    virtual void QuickSort(int beg, int end, const int mode = 0);
    int QuickSearch(const int element) const;
    int MemMove(const int dest, const int src, int count);
};

class CArrayLong : public CArray {
public:
    CArrayLong(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(const long element);
    bool AddArray(const long & src);
    bool AddArray(const CArrayLong * src);
    bool Insert(const long element, const int pos);
    bool InsertArray(const long & src, const int pos);
    bool InsertArray(const CArrayLong * src, const int pos);
    bool AssignArray(const long & src);
    bool AssignArray(const CArrayLong * src);
    long At(const int index) const;
    bool Update(const int index, const long element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    bool CompareArray(const long & array) const;
    bool CompareArray(const CArrayLong * array) const;
    bool InsertSort(const long element);
    int Search(const long element) const;
    int SearchGreat(const long element) const;
    int SearchLess(const long element) const;
    int SearchGreatOrEqual(const long element) const;
    int SearchLessOrEqual(const long element) const;
    int SearchFirst(const long element) const;
    int SearchLast(const long element) const;
    int SearchLinear(const long element) const;
protected:
    long m_data;
    virtual void QuickSort(int beg, int end, const int mode = 0);
    int QuickSearch(const long element) const;
    int MemMove(const int dest, const int src, int count);
};

class CArrayObj : public CArray {
public:
    CArrayObj(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(CObject * element);
    bool AddArray(const CArrayObj * src);
    bool Insert(CObject * element, const int pos);
    bool InsertArray(const CArrayObj * src, const int pos);
    bool AssignArray(const CArrayObj * src);
    bool Update(const int index, CObject * element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    void Clear(void);
    bool CompareArray(const CArrayObj * array) const;
    bool InsertSort(CObject * element);
    int Search(const CObject * element) const;
    int SearchGreat(const CObject * element) const;
    int SearchLess(const CObject * element) const;
    int SearchGreatOrEqual(const CObject * element) const;
    int SearchLessOrEqual(const CObject * element) const;
    int SearchFirst(const CObject * element) const;
    int SearchLast(const CObject * element) const;
protected:
    bool m_free_mode;
    void QuickSort(int beg, int end, const int mode);
    int QuickSearch(const CObject * element) const;
    int MemMove(const int dest, const int src, int count);
};

class CArrayShort : public CArray {
public:
    CArrayShort(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(const short element);
    bool AddArray(const short & src);
    bool AddArray(const CArrayShort * src);
    bool Insert(const short element, const int pos);
    bool InsertArray(const short & src, const int pos);
    bool InsertArray(const CArrayShort * src, const int pos);
    bool AssignArray(const short & src);
    bool AssignArray(const CArrayShort * src);
    short At(const int index) const;
    bool Update(const int index, const short element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    bool CompareArray(const short & array) const;
    bool CompareArray(const CArrayShort * array) const;
    bool InsertSort(const short element);
    int Search(const short element) const;
    int SearchGreat(const short element) const;
    int SearchLess(const short element) const;
    int SearchGreatOrEqual(const short element) const;
    int SearchLessOrEqual(const short element) const;
    int SearchFirst(const short element) const;
    int SearchLast(const short element) const;
    int SearchLinear(const short element) const;
protected:
    short m_data;
    virtual void QuickSort(int beg, int end, const int mode = 0);
    int QuickSearch(const short element) const;
    int MemMove(const int dest, const int src, int count);
};

class CArrayString : public CArray {
public:
    CArrayString(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(const string element);
    bool AddArray(const string & src);
    bool AddArray(const CArrayString * src);
    bool Insert(const string element, const int pos);
    bool InsertArray(const string & src, const int pos);
    bool InsertArray(const CArrayString * src, const int pos);
    bool AssignArray(const string & src);
    bool AssignArray(const CArrayString * src);
    string At(const int index) const;
    bool Update(const int index, const string element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    bool CompareArray(const string & array) const;
    bool CompareArray(const CArrayString * array) const;
    bool InsertSort(const string element);
    int Search(const string element) const;
    int SearchGreat(const string element) const;
    int SearchLess(const string element) const;
    int SearchGreatOrEqual(const string element) const;
    int SearchLessOrEqual(const string element) const;
    int SearchFirst(const string element) const;
    int SearchLast(const string element) const;
    int SearchLinear(const string element) const;
protected:
    string m_data;
    virtual void QuickSort(int beg, int end, const int mode = 0);
    int QuickSearch(const string element) const;
    int MemMove(const int dest, const int src, int count);
};

class CArrayUChar : public CArray {
public:
    CArrayUChar(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(const uchar element);
    bool AddArray(const uchar & src);
    bool AddArray(const CArrayUChar * src);
    bool Insert(const uchar element, const int pos);
    bool InsertArray(const uchar & src, const int pos);
    bool InsertArray(const CArrayUChar * src, const int pos);
    bool AssignArray(const uchar & src);
    bool AssignArray(const CArrayUChar * src);
    uchar At(const int index) const;
    bool Update(const int index, const uchar element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    bool CompareArray(const uchar & array) const;
    bool CompareArray(const CArrayUChar * array) const;
    bool InsertSort(const uchar element);
    int Search(const uchar element) const;
    int SearchGreat(const uchar element) const;
    int SearchLess(const uchar element) const;
    int SearchGreatOrEqual(const uchar element) const;
    int SearchLessOrEqual(const uchar element) const;
    int SearchFirst(const uchar element) const;
    int SearchLast(const uchar element) const;
    int SearchLinear(const uchar element) const;
protected:
    uchar m_data;
    virtual void QuickSort(int beg, int end, const int mode = 0);
    int QuickSearch(const uchar element) const;
    int MemMove(const int dest, const int src, int count);
};

class CArrayUInt : public CArray {
public:
    CArrayUInt(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(const uint element);
    bool AddArray(const uint & src);
    bool AddArray(const CArrayUInt * src);
    bool Insert(const uint element, const int pos);
    bool InsertArray(const uint & src, const int pos);
    bool InsertArray(const CArrayUInt * src, const int pos);
    bool AssignArray(const uint & src);
    bool AssignArray(const CArrayUInt * src);
    uint At(const int index) const;
    bool Update(const int index, const uint element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    bool CompareArray(const uint & array) const;
    bool CompareArray(const CArrayUInt * array) const;
    bool InsertSort(const uint element);
    int Search(const uint element) const;
    int SearchGreat(const uint element) const;
    int SearchLess(const uint element) const;
    int SearchGreatOrEqual(const uint element) const;
    int SearchLessOrEqual(const uint element) const;
    int SearchFirst(const uint element) const;
    int SearchLast(const uint element) const;
    int SearchLinear(const uint element) const;
protected:
    uint m_data;
    virtual void QuickSort(int beg, int end, const int mode = 0);
    int QuickSearch(const uint element) const;
    int MemMove(const int dest, const int src, int count);
};

class CArrayULong : public CArray {
public:
    CArrayULong(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(const ulong element);
    bool AddArray(const ulong & src);
    bool AddArray(const CArrayULong * src);
    bool Insert(const ulong element, const int pos);
    bool InsertArray(const ulong & src, const int pos);
    bool InsertArray(const CArrayULong * src, const int pos);
    bool AssignArray(const ulong & src);
    bool AssignArray(const CArrayULong * src);
    ulong At(const int index) const;
    bool Update(const int index, const ulong element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    bool CompareArray(const ulong & array) const;
    bool CompareArray(const CArrayULong * array) const;
    bool InsertSort(const ulong element);
    int Search(const ulong element) const;
    int SearchGreat(const ulong element) const;
    int SearchLess(const ulong element) const;
    int SearchGreatOrEqual(const ulong element) const;
    int SearchLessOrEqual(const ulong element) const;
    int SearchFirst(const ulong element) const;
    int SearchLast(const ulong element) const;
    int SearchLinear(const ulong element) const;
protected:
    ulong m_data;
    virtual void QuickSort(int beg, int end, const int mode = 0);
    int QuickSearch(const ulong element) const;
    int MemMove(const int dest, const int src, int count);
};

class CArrayUShort : public CArray {
public:
    CArrayUShort(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    bool Reserve(const int size);
    bool Resize(const int size);
    bool Shutdown(void);
    bool Add(const ushort element);
    bool AddArray(const ushort & src);
    bool AddArray(const CArrayUShort * src);
    bool Insert(const ushort element, const int pos);
    bool InsertArray(const ushort & src, const int pos);
    bool InsertArray(const CArrayUShort * src, const int pos);
    bool AssignArray(const ushort & src);
    bool AssignArray(const CArrayUShort * src);
    ushort At(const int index) const;
    bool Update(const int index, const ushort element);
    bool Shift(const int index, const int shift);
    bool Delete(const int index);
    bool DeleteRange(int from, int to);
    bool CompareArray(const ushort & array) const;
    bool CompareArray(const CArrayUShort * array) const;
    bool InsertSort(const ushort element);
    int Search(const ushort element) const;
    int SearchGreat(const ushort element) const;
    int SearchLess(const ushort element) const;
    int SearchGreatOrEqual(const ushort element) const;
    int SearchLessOrEqual(const ushort element) const;
    int SearchFirst(const ushort element) const;
    int SearchLast(const ushort element) const;
    int SearchLinear(const ushort element) const;
protected:
    ushort m_data;
    virtual void QuickSort(int beg, int end, const int mode = 0);
    int QuickSearch(const ushort element) const;
    int MemMove(const int dest, const int src, int count);
};

class CList : public CObject {
public:
    CList(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
    int Add(CObject * new_node);
    int Insert(CObject * new_node, int index);
    int IndexOf(CObject * node);
    bool DeleteCurrent(void);
    bool Delete(int index);
    void Clear(void);
    bool CompareList(CList * List);
    void Sort(int mode);
    bool MoveToIndex(int index);
    bool Exchange(CObject * node1, CObject * node2);
protected:
    int m_curr_idx;
    int m_data_total;
    bool m_free_mode;
    bool m_data_sort;
    int m_sort_mode;
    void QuickSort(int beg, int end, int mode);
};

class CTreeNode : public CObject {
public:
    CTreeNode(void);
    int RefreshBalance(void);
    bool SaveNode(const int file_handle);
    bool LoadNode(const int file_handle, CTreeNode * main);
};

class CTree : public CTreeNode {
public:
    CTree(void);
    bool Detach(CTreeNode * node);
    bool Delete(CTreeNode * node);
    void Clear(void);
    virtual bool Save(const int file_handle);
    virtual bool Load(const int file_handle);
protected:
    void Balance(CTreeNode * node);
};

class CChart {
public:
    CChart(void);
    bool Attach(const long chart_id);
    bool Detach(void);
    long GetId(void) const;
    int GetHandle(void) const;
    bool Refresh(void);
    bool ApplyTemplate(const string filename);
    int WindowHandle(const int sub_window = 0) const;
    long WindowOnDropped(void) const;
    int SubwindowOnDropped(void) const;
    int XOnDropped(void) const;
    int YOnDropped(void) const;
    int Width(void) const;
    int Height(void) const;
    int WidthInPixels(void) const;
    int HeightInPixels(void) const;
    int WidthInPixels(const int sub_window) const;
    int HeightInPixels(const int sub_window) const;
    bool BringToTop(void);
    bool BringToTop(const int sub_window);
    bool SetInteger(const ENUM_CHART_PROPERTY_INTEGER prop_id, const long value);
    bool SetInteger(const ENUM_CHART_PROPERTY_INTEGER prop_id, const int sub_window, const long value);
    bool SetDouble(const ENUM_CHART_PROPERTY_DOUBLE prop_id, const double value);
    bool SetDouble(const ENUM_CHART_PROPERTY_DOUBLE prop_id, const int sub_window, const double value);
    bool SetString(const ENUM_CHART_PROPERTY_STRING prop_id, const string value);
    bool SetString(const ENUM_CHART_PROPERTY_STRING prop_id, const int sub_window, const string value);
    long GetInteger(const ENUM_CHART_PROPERTY_INTEGER prop_id) const;
    long GetInteger(const ENUM_CHART_PROPERTY_INTEGER prop_id, const int sub_window) const;
    double GetDouble(const ENUM_CHART_PROPERTY_DOUBLE prop_id) const;
    double GetDouble(const ENUM_CHART_PROPERTY_DOUBLE prop_id, const int sub_window) const;
    string GetString(const ENUM_CHART_PROPERTY_STRING prop_id) const;
    string GetString(const ENUM_CHART_PROPERTY_STRING prop_id, const int sub_window) const;
    bool SetSymbolPeriod(const string symbol, const ENUM_TIMEFRAMES period);
    bool SetPeriod(const ENUM_TIMEFRAMES period);
    bool SetSymbol(const string symbol);
    string Symbol(void) const;
    ENUM_TIMEFRAMES Period(void) const;
    int PeriodSeconds(void) const;
    int VisibleBars(void) const;
    int WindowsTotal(void) const;
    bool ScreenShot(const string filename, const int width, const int height, const ENUM_ALIGN_MODE align_mode = ALIGN_RIGHT);
    bool ScreenShot(const string filename, const int width, const int height, const ENUM_ALIGN_MODE align_mode, const int scale_percent);
    bool ScreenShot(const string filename, const int width, const int height, const ENUM_ALIGN_MODE align_mode, const int scale_percent, const int scale_type);
    bool Navigate(const ENUM_CHART_POSITION chart_position);
    bool Navigate(const datetime date, const long shift = 0);
    bool SetTimeScale(const int scale);
    int GetTimeScale(void) const;
    bool SetIntegerAxis(const bool value);
    bool SetIntegerAxis(const bool value, const int sub_window);
    bool GetIntegerAxis(void) const;
    bool GetIntegerAxis(const int sub_window) const;
    bool SetDoubleAxis(const double min, const double max);
    bool SetDoubleAxis(const double min, const double max, const int sub_window);
    bool GetDoubleAxis(double & min, double & max) const;
    bool GetDoubleAxis(double & min, double & max, const int sub_window) const;
    bool IndicatorAdd(const int sub_window, int indicator_handle);
    bool IndicatorDelete(const int sub_window, int indicator_handle);
    int IndicatorRelease(int indicator_handle);
    int IndicatorsTotal(const int sub_window = 0) const;
    bool WindowIsVisible(const int sub_window) const;
    bool WindowIsVisible(void) const;
    int WindowFirstVisibleBar(const int sub_window = 0) const;
    int WindowBarsPerChart(void) const;
    int WindowBarsPerChart(const int sub_window) const;
    int WindowYDistance(const int sub_window) const;
    int WindowXDistance(const int sub_window) const;
protected:
    long m_chart_id;
    int m_chart_handle;
};

#endif // __clang__
