/**
 * Auto-generated MQL5 Standard Library stubs for clangd
 * Generated: 2026-01-12T22:02:46.242Z
 * 
 * DO NOT EDIT - This file is auto-generated by mql-stub-generator
 */

#pragma once

#ifdef __clang__

// Typedefs for MQL5 types
typedef long datetime;
typedef unsigned long ulong;
typedef unsigned int uint;

// Forward declarations
class CObject;
class CWndObj;
class CWndContainer;
class CPositionInfo;
class COrderInfo;
class CTrade;

// Enums
enum ENUM_POSITION_TYPE {
    POSITION_TYPE_BUY = 0,
    POSITION_TYPE_SELL = 1
};

enum ENUM_ORDER_TYPE {
    ORDER_TYPE_BUY = 0,
    ORDER_TYPE_SELL = 1,
    ORDER_TYPE_BUY_LIMIT = 2,
    ORDER_TYPE_SELL_LIMIT = 3,
    ORDER_TYPE_BUY_STOP = 4,
    ORDER_TYPE_SELL_STOP = 5,
    ORDER_TYPE_BUY_STOP_LIMIT = 6,
    ORDER_TYPE_SELL_STOP_LIMIT = 7,
    ORDER_TYPE_CLOSE_BY = 8
};

enum ENUM_ORDER_STATE {
    ORDER_STATE_STARTED = 0,
    ORDER_STATE_PLACED = 1,
    ORDER_STATE_CANCELED = 2,
    ORDER_STATE_PARTIAL = 3,
    ORDER_STATE_FILLED = 4,
    ORDER_STATE_REJECTED = 5,
    ORDER_STATE_EXPIRED = 6,
    ORDER_STATE_REQUEST_ADD = 7,
    ORDER_STATE_REQUEST_MODIFY = 8,
    ORDER_STATE_REQUEST_CANCEL = 9
};

enum ENUM_ORDER_TYPE_FILLING {
    ORDER_FILLING_FOK = 0,
    ORDER_FILLING_IOC = 1,
    ORDER_FILLING_RETURN = 2
};

enum ENUM_ORDER_TYPE_TIME {
    ORDER_TIME_GTC = 0,
    ORDER_TIME_DAY = 1,
    ORDER_TIME_SPECIFIED = 2,
    ORDER_TIME_SPECIFIED_DAY = 3
};

enum ENUM_POSITION_PROPERTY_INTEGER {
    POSITION_PROP_INTEGER_VOLUME = 0,
    POSITION_PROP_INTEGER_TYPE = 1,
    POSITION_PROP_INTEGER_MAGIC = 2,
    POSITION_PROP_INTEGER_IDENTIFIER = 3,
    POSITION_PROP_INTEGER_TIME = 4,
    POSITION_PROP_INTEGER_TIME_MSC = 5,
    POSITION_PROP_INTEGER_TIME_UPDATE = 6,
    POSITION_PROP_INTEGER_TIME_UPDATE_MSC = 7
};

enum ENUM_POSITION_PROPERTY_DOUBLE {
    POSITION_PROP_DOUBLE_PRICE_OPEN = 0,
    POSITION_PROP_DOUBLE_PRICE_CURRENT = 1,
    POSITION_PROP_DOUBLE_SL = 2,
    POSITION_PROP_DOUBLE_TP = 3,
    POSITION_PROP_DOUBLE_PROFIT = 4,
    POSITION_PROP_DOUBLE_COMMISSION = 5,
    POSITION_PROP_DOUBLE_SWAP = 6,
    POSITION_PROP_DOUBLE_VOLUME = 7
};

enum ENUM_POSITION_PROPERTY_STRING {
    POSITION_PROP_STRING_SYMBOL = 0,
    POSITION_PROP_STRING_COMMENT = 1
};

enum ENUM_ORDER_PROPERTY_INTEGER {
    ORDER_PROP_INTEGER_VOLUME = 0,
    ORDER_PROP_INTEGER_TYPE = 1,
    ORDER_PROP_INTEGER_STATE = 2,
    ORDER_PROP_INTEGER_TIME_SETUP = 3,
    ORDER_PROP_INTEGER_TIME_SETUP_MSC = 4,
    ORDER_PROP_INTEGER_TIME_DONE = 5,
    ORDER_PROP_INTEGER_TIME_DONE_MSC = 6,
    ORDER_PROP_INTEGER_TIME_EXPIRATION = 7,
    ORDER_PROP_INTEGER_TYPE_FILLING = 8,
    ORDER_PROP_INTEGER_TYPE_TIME = 9,
    ORDER_PROP_INTEGER_MAGIC = 10,
    ORDER_PROP_INTEGER_POSITION_ID = 11,
    ORDER_PROP_INTEGER_POSITION_BY_ID = 12
};

enum ENUM_ORDER_PROPERTY_DOUBLE {
    ORDER_PROP_DOUBLE_VOLUME = 0,
    ORDER_PROP_DOUBLE_PRICE_OPEN = 1,
    ORDER_PROP_DOUBLE_SL = 2,
    ORDER_PROP_DOUBLE_TP = 3,
    ORDER_PROP_DOUBLE_PRICE_CURRENT = 4,
    ORDER_PROP_DOUBLE_PRICE_STOP_LIMIT = 5
};

enum ENUM_ORDER_PROPERTY_STRING {
    ORDER_PROP_STRING_SYMBOL = 0,
    ORDER_PROP_STRING_COMMENT = 1
};

enum ENUM_TRADE_REQUEST_ACTIONS {
    TRADE_ACTION_DEAL = 0,
    TRADE_ACTION_PENDING = 1,
    TRADE_ACTION_SLTP = 2,
    TRADE_ACTION_MODIFY = 3,
    TRADE_ACTION_REMOVE = 4,
    TRADE_ACTION_CLOSE_BY = 5
};

// Classes
class CWndObj : public CObject {
public:
    CWndObj(void);
    virtual bool Create(const long chart, const string name, const int subwin, const int x1, const int y1, const int x2, const int y2);
    virtual bool Destroy(void);
    virtual bool Move(const int x, const int y);
    virtual bool Size(const int w, const int h);
    virtual bool Shift(const int dx, const int dy);
    long ChartId(void) const;
    int SubWindow(void) const;
    string Name(void) const;
    int Left(void) const;
    int Top(void) const;
    int Right(void) const;
    int Bottom(void) const;
    int Width(void) const;
    int Height(void) const;
    virtual bool Show(void);
    virtual bool Hide(void);
    bool IsVisible(void) const;
    virtual bool Enable(void);
    virtual bool Disable(void);
    bool IsEnabled(void) const;
    long Z_Order(void) const;
    bool Z_Order(const long value);
protected:
    long m_chart_id;
    int m_subwin;
    string m_name;
    int m_x;
    int m_y;
    int m_w;
    int m_h;
    bool m_visible;
    bool m_enabled;
    virtual bool OnCreate(void);
    virtual bool OnDestroy(void);
    virtual bool OnMove(void);
    virtual bool OnResize(void);
    virtual bool OnShow(void);
    virtual bool OnHide(void);
    virtual bool OnEnable(void);
    virtual bool OnDisable(void);
};

class CWndContainer : public CWndObj {
public:
    CWndContainer(void);
    virtual bool Add(CWndObj * control);
    virtual bool Add(CWndObj & control);
    int ControlsTotal(void) const;
    CWndObj* Control(const int index) const;
    CWndObj* ControlFind(const string name);
    virtual bool Delete(CWndObj * control);
    virtual bool Delete(const int index);
    virtual bool OnEvent(const int id, const long & lparam, const double & dparam, const string & sparam);
    virtual void Redraw(void);
    virtual bool Save(const int handle);
    virtual bool Load(const int handle);
protected:
    struct CArrayObj m_controls;
    virtual bool OnCreate(void);
    virtual bool OnDestroy(void);
    virtual bool OnMove(void);
    virtual bool OnResize(void);
    virtual bool OnShow(void);
    virtual bool OnHide(void);
    virtual bool OnEnable(void);
    virtual bool OnDisable(void);
};

class CPositionInfo : public CObject {
public:
    CPositionInfo(void);
    ulong Ticket(void) const;
    datetime Time(void) const;
    ulong TimeMsc(void) const;
    datetime TimeUpdate(void) const;
    ulong TimeUpdateMsc(void) const;
    ENUM_POSITION_TYPE PositionType(void) const;
    string TypeDescription(void) const;
    long Magic(void) const;
    long Identifier(void) const;
    double Volume(void) const;
    double PriceOpen(void) const;
    double StopLoss(void) const;
    double TakeProfit(void) const;
    double PriceCurrent(void) const;
    double Commission(void) const;
    double Swap(void) const;
    double Profit(void) const;
    string Symbol(void) const;
    string Comment(void) const;
    bool InfoInteger(const ENUM_POSITION_PROPERTY_INTEGER prop_id, long & var) const;
    bool InfoDouble(const ENUM_POSITION_PROPERTY_DOUBLE prop_id, double & var) const;
    bool InfoString(const ENUM_POSITION_PROPERTY_STRING prop_id, string & var) const;
    bool Select(const string symbol);
    bool SelectByIndex(const int index);
    bool SelectByMagic(const string symbol, const ulong magic);
    bool SelectByTicket(const ulong ticket);
    void StoreState(void);
    bool CheckState(void);
protected:
    string m_symbol;
};

class COrderInfo : public CObject {
public:
    COrderInfo(void);
    ulong Ticket(void) const;
    datetime TimeSetup(void) const;
    ulong TimeSetupMsc(void) const;
    datetime TimeDone(void) const;
    ulong TimeDoneMsc(void) const;
    ENUM_ORDER_TYPE OrderType(void) const;
    string TypeDescription(void) const;
    ENUM_ORDER_STATE State(void) const;
    string StateDescription(void) const;
    datetime TimeExpiration(void) const;
    ENUM_ORDER_TYPE_FILLING TypeFilling(void) const;
    string TypeFillingDescription(void) const;
    ENUM_ORDER_TYPE_TIME TypeTime(void) const;
    string TypeTimeDescription(void) const;
    long Magic(void) const;
    long PositionId(void) const;
    long PositionById(void) const;
    double VolumeInitial(void) const;
    double VolumeCurrent(void) const;
    double PriceOpen(void) const;
    double StopLoss(void) const;
    double TakeProfit(void) const;
    double PriceCurrent(void) const;
    double PriceStopLimit(void) const;
    string Symbol(void) const;
    string Comment(void) const;
    bool InfoInteger(const ENUM_ORDER_PROPERTY_INTEGER prop_id, long & var) const;
    bool InfoDouble(const ENUM_ORDER_PROPERTY_DOUBLE prop_id, double & var) const;
    bool InfoString(const ENUM_ORDER_PROPERTY_STRING prop_id, string & var) const;
    bool Select(const ulong ticket);
    bool SelectByIndex(const int index);
    void StoreState(void);
    bool CheckState(void);
protected:
    ulong m_ticket;
};

class CTrade : public CObject {
public:
    CTrade(void);
    void SetExpertMagicNumber(const ulong magic);
    void SetDeviationInPoints(const ulong deviation);
    void SetTypeFilling(const ENUM_ORDER_TYPE_FILLING filling);
    void SetTypeFillingBySymbol(const string symbol);
    void SetOrderExpiration(const datetime expiration);
    void SetMarginMode(void);
    void SetAsyncMode(const bool mode);
    void SetLogLevel(const int log_level);
    ulong RequestMagic(void) const;
    ulong RequestDeviation(void) const;
    ENUM_ORDER_TYPE_FILLING RequestTypeFilling(void) const;
    bool PositionOpen(const string symbol, const ENUM_ORDER_TYPE order_type, const double volume, const double price, const double sl, const double tp, const string comment = "");
    bool PositionModify(const string symbol, const double sl, const double tp);
    bool PositionModify(const ulong ticket, const double sl, const double tp);
    bool PositionClose(const string symbol, const ulong deviation = ULONG_MAX);
    bool PositionClose(const ulong ticket, const ulong deviation = ULONG_MAX);
    bool PositionCloseBy(const ulong ticket, const ulong ticket_by);
    bool PositionClosePartial(const string symbol, const double volume, const ulong deviation = ULONG_MAX);
    bool PositionClosePartial(const ulong ticket, const double volume, const ulong deviation = ULONG_MAX);
    bool OrderOpen(const string symbol, const ENUM_ORDER_TYPE order_type, const double volume, const double limit_price, const double price, const double sl, const double tp, ENUM_ORDER_TYPE_TIME type_time = ORDER_TIME_GTC, const datetime expiration = 0, const string comment = "");
    bool OrderModify(const ulong ticket, const double price, const double sl, const double tp, const ENUM_ORDER_TYPE_TIME type_time, const datetime expiration, const double stoplimit = 0.0);
    bool OrderDelete(const ulong ticket);
    uint ResultRetcode(void) const;
    ulong ResultDeal(void) const;
    ulong ResultOrder(void) const;
    double ResultVolume(void) const;
    double ResultPrice(void) const;
    double ResultBid(void) const;
    double ResultAsk(void) const;
    string ResultComment(void) const;
    uint ResultRetcodeDescription(string & description) const;
    ENUM_TRADE_REQUEST_ACTIONS RequestAction(void) const;
    string RequestSymbol(void) const;
    double RequestVolume(void) const;
    double RequestPrice(void) const;
    double RequestSL(void) const;
    double RequestTP(void) const;
    string RequestComment(void) const;
    bool Buy(const double volume, const string symbol = NULL, double price = 0.0, const double sl = 0.0, const double tp = 0.0, const string comment = "");
    bool Sell(const double volume, const string symbol = NULL, double price = 0.0, const double sl = 0.0, const double tp = 0.0, const string comment = "");
    bool BuyLimit(const double volume, const double price, const string symbol = NULL, const double sl = 0.0, const double tp = 0.0, const ENUM_ORDER_TYPE_TIME type_time = ORDER_TIME_GTC, const datetime expiration = 0, const string comment = "");
    bool SellLimit(const double volume, const double price, const string symbol = NULL, const double sl = 0.0, const double tp = 0.0, const ENUM_ORDER_TYPE_TIME type_time = ORDER_TIME_GTC, const datetime expiration = 0, const string comment = "");
    bool BuyStop(const double volume, const double price, const string symbol = NULL, const double sl = 0.0, const double tp = 0.0, const ENUM_ORDER_TYPE_TIME type_time = ORDER_TIME_GTC, const datetime expiration = 0, const string comment = "");
    bool SellStop(const double volume, const double price, const string symbol = NULL, const double sl = 0.0, const double tp = 0.0, const ENUM_ORDER_TYPE_TIME type_time = ORDER_TIME_GTC, const datetime expiration = 0, const string comment = "");
protected:
    struct MqlTradeRequest {
        int action;
        int magic;
        int order;
        int symbol;
        int volume;
        double price;
        double sl;
        double tp;
        int deviation;
        int type;
        int type_filling;
        int type_time;
        datetime expiration;
        double stoplimit;
    } m_request;
    struct MqlTradeResult {
        int retcode;
        ulong deal;
        ulong order;
        double volume;
        double price;
        double bid;
        double ask;
        string comment;
    } m_result;
    bool m_async_mode;
    ulong m_magic;
    ulong m_deviation;
    ENUM_ORDER_TYPE_FILLING m_type_filling;
    ENUM_ORDER_TYPE_TIME m_type_time;
    datetime m_expiration;
    string m_comment;
    int m_log_level;
    bool PositionOpenCheck(const string symbol);
    bool OrderTypeCheck(const string symbol);
    void ClearStructures(void);
    bool SelectPosition(const string symbol);
};

#endif // __clang__
