/**
 * Auto-generated MQL5 Standard Library stubs for clangd
 * Generated: 2026-01-12T22:20:16.909Z
 * 
 * DO NOT EDIT - This file is auto-generated by mql-stub-generator
 */

#pragma once

#ifdef __clang__

// Forward declarations
class CAccountInfo;
class CDealInfo;
class CHistoryOrderInfo;
class COrderInfo;
class CPositionInfo;
class CSymbolInfo;
class CTerminalInfo;
class CTrade;
class CBmpButton;
class CButton;
class CCheckBox;
class CCheckGroup;
class CComboBox;
class CDateDropList;
class CDatePicker;
class CDialog;
class CAppDialog;
class CEdit;
class CLabel;
class CListView;
class CPanel;
class CPicture;
class CRadioButton;
class CRadioGroup;
class CPoint;
class CSize;
class CRect;
class CScroll;
class CScrollV;
class CScrollH;
class CSpinEdit;
class CWnd;
class CDragWnd;
class CWndClient;
class CWndContainer;
class CWndObj;
class CArray;
class CArrayChar;
class CArrayColor;
class CArrayDatetime;
class CArrayDouble;
class CArrayFloat;
class CArrayInt;
class CArrayLong;
class CArrayObj;
class CArrayShort;
class CArrayString;
class CArrayUChar;
class CArrayUInt;
class CArrayULong;
class CArrayUShort;
class CList;
class CTree;
class CTreeNode;

// Enums
enum ENUM_LOG_LEVELS {
    LOG_LEVEL_NO = 0,
    LOG_LEVEL_ERRORS = 1,
    LOG_LEVEL_ALL = 2
};

enum ENUM_DATE_MODES {
    DATE_MODE_MON,
    DATE_MODE_YEAR
};

enum ENUM_WND_PROP_FLAGS {
    WND_PROP_FLAG_CAN_DBL_CLICK = 1,
    WND_PROP_FLAG_CAN_DRAG = 2,
    WND_PROP_FLAG_CLICKS_BY_PRESS = 4,
    WND_PROP_FLAG_CAN_LOCK = 8,
    WND_PROP_FLAG_READ_ONLY = 16
};

enum ENUM_WND_STATE_FLAGS {
    WND_STATE_FLAG_ENABLE = 1,
    WND_STATE_FLAG_VISIBLE = 2,
    WND_STATE_FLAG_ACTIVE = 4
};

enum ENUM_MOUSE_FLAGS {
    MOUSE_INVALID_FLAGS = -1,
    MOUSE_EMPTY = 0,
    MOUSE_LEFT = 1,
    MOUSE_RIGHT = 2
};

enum ENUM_WND_ALIGN_FLAGS {
    WND_ALIGN_NONE = 0,
    WND_ALIGN_LEFT = 1,
    WND_ALIGN_TOP = 2,
    WND_ALIGN_RIGHT = 4,
    WND_ALIGN_BOTTOM = 8,
    WND_ALIGN_WIDTH = WND_ALIGN_LEFT|WND_ALIGN_RIGHT,
    WND_ALIGN_HEIGHT = WND_ALIGN_TOP|WND_ALIGN_BOTTOM,
    WND_ALIGN_CLIENT = WND_ALIGN_WIDTH|WND_ALIGN_HEIGHT
};

// Forward declarations only mode - no class definitions
// Include actual MQL5 headers for full definitions

#endif // __clang__
