/**
 * MQL Compatibility Header for Clangd (v11)
 *
 * Provides type definitions, function stubs, and Standard Library stubs
 * for clangd IntelliSense support in MQL4/MQL5 projects.
 *
 * Issue #14: This is a fork of MQL Tools with clangd support.
 * The definitions in this file are built from ground up for clangd compatibility,
 * not derived from the original MQL Tools. This ensures optimal IntelliSense,
 * code completion, and semantic analysis for MQL4/5 projects.
 *
 * Key differences from original:
 * - Custom MQL type definitions optimized for clangd
 * - Comprehensive enum and constant declarations
 * - Proper C++ semantics for MQL constructs
 * - Support for MQL-specific features (pack(), flexible arrays, etc.)
 */

#pragma once

#ifdef __clang__

// MQL input/sinput keywords for parameter declarations
// These are storage-class specifiers in MQL that clangd doesn't recognize
#define input
#define sinput static

// MQL5 struct packing syntax: struct NAME pack(n) { ... }
// Clangd doesn't understand this, so we strip it
#define pack(n) /* MQL5 pack stripped for clangd */

// MQL export keyword for function declarations
// Used to export functions from DLLs or make them accessible to other modules
#define export /* MQL export stripped for clangd */

// Use a class for string to handle literals, assignments, and operations without warnings
class _mql_string {
public:
    _mql_string() {}
    _mql_string(const char* s) {}
    _mql_string(const _mql_string& other) {}

    // Support casting from common MQL types
    _mql_string(long long val) {}
    _mql_string(int val) {}
    _mql_string(double val) {}

    _mql_string& operator=(const char* s) { return *this; }
    _mql_string& operator=(const _mql_string& s) { return *this; }

    bool operator==(const char* s) const { return true; }
    bool operator==(const _mql_string& s) const { return true; }
    bool operator==(int) const { return true; }  // Handle string == NULL (NULL is 0 in C++)
    bool operator!=(const char* s) const { return false; }
    bool operator!=(const _mql_string& s) const { return false; }
    bool operator!=(int) const { return false; } // Handle string != NULL

    _mql_string operator+(const char* s) const { return *this; }
    _mql_string operator+(const _mql_string& s) const { return *this; }
    _mql_string& operator+=(const char* s) { return *this; }
    _mql_string& operator+=(const _mql_string& s) { return *this; }

    // Subscript operator for character access (MQL5 strings support [])
    ushort operator[](int index) const { return 0; }
    ushort& operator[](int index) { static ushort dummy = 0; return dummy; }

    // Conversion operators to handle MQL's loose typing
    operator int() const { return 0; }
    operator long() const { return 0; }
    operator double() const { return 0.0; }

    friend _mql_string operator+(const char* s, const _mql_string& ms) { return ms; }
};
typedef _mql_string string;

typedef long long datetime;
typedef unsigned int color;
typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned int uint;
typedef unsigned long long ulong;

// Socket types - guarded to avoid conflicts with user socket libraries
#ifndef SOCKET64
typedef int SOCKET64;
#endif
#ifndef INVALID_SOCKET64
#define INVALID_SOCKET64 -1
#endif

// Socket address structures (for low-level socket APIs)
#ifndef _SOCKADDR_IN_DEFINED
#define _SOCKADDR_IN_DEFINED
struct sockaddr_in {
    short sin_family;
    ushort sin_port;
    uint sin_addr;
    char sin_zero[8];
};
#endif // _SOCKADDR_IN_DEFINED

#ifndef _REF_SOCKADDR_DEFINED
#define _REF_SOCKADDR_DEFINED
union ref_sockaddr {
    sockaddr_in in;
    uchar ref[16];
};

union ref_sockaddr_in {
    sockaddr_in in;
    uchar ref[16];
};
#endif // _REF_SOCKADDR_DEFINED

// Windows structures (for DLL interop)
struct CREATESTRUCTW {
    long lpCreateParams;
    long hInstance;
    long hMenu;
    long hwndParent;
    int cy;
    int cx;
    int y;
    int x;
    long style;
    string lpszName;
    string lpszClass;
    uint dwExStyle;
};

// Restoring essential MQL types that are built-in
struct MqlDateTime { int year, mon, day, hour, min, sec, day_of_week, day_of_year; };

// MQL5 Trading structures
struct MqlTradeRequest {
    int action;
    ulong magic;
    ulong order;
    string symbol;
    double volume;
    double price;
    double stoplimit;
    double sl;
    double tp;
    ulong deviation;
    int type;
    int type_filling;
    int type_time;
    datetime expiration;
    string comment;
    ulong position;
    ulong position_by;
};

struct MqlTradeResult {
    uint retcode;
    ulong deal;
    ulong order;
    double volume;
    double price;
    double bid;
    double ask;
    string comment;
    uint request_id;
    int retcode_external;
};

#define NULL 0
#define EMPTY -1
#define WRONG_VALUE -1
#define clrNONE 0xFFFFFF

enum ENUM_TIMEFRAMES { PERIOD_CURRENT=0, PERIOD_M1=1, PERIOD_M2=2, PERIOD_M3=3, PERIOD_M4=4, PERIOD_M5=5, PERIOD_M6=6, PERIOD_M10=10, PERIOD_M12=12, PERIOD_M15=15, PERIOD_M20=20, PERIOD_M30=30, PERIOD_H1=16385, PERIOD_H2=16386, PERIOD_H3=16387, PERIOD_H4=16388, PERIOD_H6=16390, PERIOD_H8=16392, PERIOD_H12=16396, PERIOD_D1=16408, PERIOD_W1=32769, PERIOD_MN1=49153 };

// Trade related enums
enum ENUM_ORDER_TYPE { ORDER_TYPE_BUY=0, ORDER_TYPE_SELL=1, ORDER_TYPE_BUY_LIMIT=2, ORDER_TYPE_SELL_LIMIT=3, ORDER_TYPE_BUY_STOP=4, ORDER_TYPE_SELL_STOP=5, ORDER_TYPE_BUY_STOP_LIMIT=6, ORDER_TYPE_SELL_STOP_LIMIT=7, ORDER_TYPE_CLOSE_BY=8 };
enum ENUM_ORDER_STATE { ORDER_STATE_STARTED=0, ORDER_STATE_PLACED=1, ORDER_STATE_CANCELED=2, ORDER_STATE_PARTIAL=3, ORDER_STATE_FILLED=4, ORDER_STATE_REJECTED=5, ORDER_STATE_EXPIRED=6, ORDER_STATE_REQUEST_ADD=7, ORDER_STATE_REQUEST_MODIFY=8, ORDER_STATE_REQUEST_CANCEL=9 };
enum ENUM_ORDER_TYPE_FILLING { ORDER_FILLING_FOK=0, ORDER_FILLING_IOC=1, ORDER_FILLING_RETURN=2, ORDER_FILLING_BOC=3 };
enum ENUM_ORDER_TYPE_TIME { ORDER_TIME_GTC=0, ORDER_TIME_DAY=1, ORDER_TIME_SPECIFIED=2, ORDER_TIME_SPECIFIED_DAY=3 };
enum ENUM_POSITION_TYPE { POSITION_TYPE_BUY=0, POSITION_TYPE_SELL=1 };
enum ENUM_DEAL_TYPE { DEAL_TYPE_BUY=0, DEAL_TYPE_SELL=1, DEAL_TYPE_BALANCE=2, DEAL_TYPE_CREDIT=3, DEAL_TYPE_CHARGE=4, DEAL_TYPE_CORRECTION=5, DEAL_TYPE_BONUS=6, DEAL_TYPE_COMMISSION=7, DEAL_TYPE_COMMISSION_DAILY=8, DEAL_TYPE_COMMISSION_MONTHLY=9, DEAL_TYPE_COMMISSION_AGENT_DAILY=10, DEAL_TYPE_COMMISSION_AGENT_MONTHLY=11, DEAL_TYPE_INTEREST=12, DEAL_TYPE_BUY_CANCELED=13, DEAL_TYPE_SELL_CANCELED=14, DEAL_DIVIDEND=15, DEAL_DIVIDEND_FRANKED=16, DEAL_TAX=17 };
enum ENUM_TRADE_REQUEST_ACTIONS { TRADE_ACTION_DEAL=1, TRADE_ACTION_PENDING=5, TRADE_ACTION_SLTP=6, TRADE_ACTION_MODIFY=7, TRADE_ACTION_REMOVE=8, TRADE_ACTION_CLOSE_BY=10 };

// Property enums for OrderGet*, PositionGet*, DealGet*, HistoryOrderGet*, etc.
enum ENUM_ORDER_PROPERTY_INTEGER { ORDER_TICKET=0, ORDER_TIME_SETUP=1, ORDER_TYPE=2, ORDER_STATE=3, ORDER_TIME_EXPIRATION=4, ORDER_TIME_DONE=5, ORDER_TIME_SETUP_MSC=6, ORDER_TIME_DONE_MSC=7, ORDER_TYPE_FILLING=8, ORDER_TYPE_TIME=9, ORDER_MAGIC=10, ORDER_REASON=11, ORDER_POSITION_ID=12, ORDER_POSITION_BY_ID=13 };
enum ENUM_ORDER_PROPERTY_DOUBLE { ORDER_VOLUME_INITIAL=0, ORDER_VOLUME_CURRENT=1, ORDER_PRICE_OPEN=2, ORDER_SL=3, ORDER_TP=4, ORDER_PRICE_CURRENT=5, ORDER_PRICE_STOPLIMIT=6 };
enum ENUM_ORDER_PROPERTY_STRING { ORDER_SYMBOL=0, ORDER_COMMENT=1, ORDER_EXTERNAL_ID=2 };

enum ENUM_POSITION_PROPERTY_INTEGER { POSITION_TICKET=0, POSITION_TIME=1, POSITION_TIME_MSC=2, POSITION_TIME_UPDATE=3, POSITION_TIME_UPDATE_MSC=4, POSITION_TYPE_PROP=5, POSITION_MAGIC=6, POSITION_IDENTIFIER=7, POSITION_REASON=8 };
enum ENUM_POSITION_PROPERTY_DOUBLE { POSITION_VOLUME=0, POSITION_PRICE_OPEN=1, POSITION_SL=2, POSITION_TP=3, POSITION_PRICE_CURRENT=4, POSITION_SWAP=5, POSITION_PROFIT=6 };
enum ENUM_POSITION_PROPERTY_STRING { POSITION_SYMBOL=0, POSITION_COMMENT=1, POSITION_EXTERNAL_ID=2 };

enum ENUM_DEAL_PROPERTY_INTEGER { DEAL_TICKET=0, DEAL_ORDER=1, DEAL_TIME=2, DEAL_TIME_MSC=3, DEAL_TYPE_PROP=4, DEAL_ENTRY=5, DEAL_MAGIC=6, DEAL_REASON=7, DEAL_POSITION_ID=8 };
enum ENUM_DEAL_PROPERTY_DOUBLE { DEAL_VOLUME=0, DEAL_PRICE=1, DEAL_COMMISSION=2, DEAL_SWAP=3, DEAL_PROFIT=4, DEAL_FEE=5, DEAL_SL=6, DEAL_TP=7 };
enum ENUM_DEAL_PROPERTY_STRING { DEAL_SYMBOL=0, DEAL_COMMENT=1, DEAL_EXTERNAL_ID=2 };

enum ENUM_DEAL_ENTRY { DEAL_ENTRY_IN=0, DEAL_ENTRY_OUT=1, DEAL_ENTRY_INOUT=2, DEAL_ENTRY_OUT_BY=3, DEAL_ENTRY_STATE=4 };
enum ENUM_DEAL_REASON {
    DEAL_REASON_CLIENT=0, DEAL_REASON_MOBILE=1, DEAL_REASON_WEB=2, DEAL_REASON_EXPERT=3,
    DEAL_REASON_SL=4, DEAL_REASON_TP=5, DEAL_REASON_SO=6, DEAL_REASON_ROLLOVER=7,
    DEAL_REASON_VMARGIN=8, DEAL_REASON_SPLIT=9, DEAL_REASON_BALANCE=10, DEAL_REASON_CREDIT=11,
    DEAL_REASON_CHARGE=12, DEAL_REASON_CORRECTION=13, DEAL_REASON_BONUS=14,
    DEAL_REASON_COMMISSION=15, DEAL_REASON_COMMISSION_DAILY=16, DEAL_REASON_COMMISSION_MONTHLY=17,
    DEAL_REASON_COMMISSION_AGENT_DAILY=18, DEAL_REASON_COMMISSION_AGENT_MONTHLY=19,
    DEAL_REASON_INTEREST=20, DEAL_REASON_DIVIDEND=21, DEAL_REASON_DIVIDEND_FRANKED=22,
    DEAL_REASON_TAX=23, DEAL_REASON_CORPORATE_ACTION=24
};
enum ENUM_ORDER_REASON { ORDER_REASON_CLIENT=0, ORDER_REASON_MOBILE=1, ORDER_REASON_WEB=2, ORDER_REASON_EXPERT=3, ORDER_REASON_SL=4, ORDER_REASON_TP=5, ORDER_REASON_SO=6 };
enum ENUM_POSITION_REASON { POSITION_REASON_CLIENT=0, POSITION_REASON_MOBILE=1, POSITION_REASON_WEB=2, POSITION_REASON_EXPERT=3 };

// Trade return codes
enum ENUM_TRADE_RETCODE { TRADE_RETCODE_REQUOTE=10004, TRADE_RETCODE_REJECT=10006, TRADE_RETCODE_CANCEL=10007, TRADE_RETCODE_PLACED=10008, TRADE_RETCODE_DONE=10009, TRADE_RETCODE_DONE_PARTIAL=10010, TRADE_RETCODE_ERROR=10011, TRADE_RETCODE_TIMEOUT=10012, TRADE_RETCODE_INVALID=10013, TRADE_RETCODE_INVALID_VOLUME=10014, TRADE_RETCODE_INVALID_PRICE=10015, TRADE_RETCODE_INVALID_STOPS=10016, TRADE_RETCODE_TRADE_DISABLED=10017, TRADE_RETCODE_MARKET_CLOSED=10018, TRADE_RETCODE_NO_MONEY=10019, TRADE_RETCODE_PRICE_CHANGED=10020, TRADE_RETCODE_PRICE_OFF=10021, TRADE_RETCODE_INVALID_EXPIRATION=10022, TRADE_RETCODE_ORDER_CHANGED=10023, TRADE_RETCODE_TOO_MANY_REQUESTS=10024, TRADE_RETCODE_NO_CHANGES=10025, TRADE_RETCODE_SERVER_DISABLES_AT=10026, TRADE_RETCODE_CLIENT_DISABLES_AT=10027, TRADE_RETCODE_LOCKED=10028, TRADE_RETCODE_FROZEN=10029, TRADE_RETCODE_INVALID_FILL=10030, TRADE_RETCODE_CONNECTION=10031, TRADE_RETCODE_ONLY_REAL=10032, TRADE_RETCODE_LIMIT_ORDERS=10033, TRADE_RETCODE_LIMIT_VOLUME=10034, TRADE_RETCODE_INVALID_ORDER=10035, TRADE_RETCODE_POSITION_CLOSED=10036, TRADE_RETCODE_INVALID_CLOSE_VOLUME=10038, TRADE_RETCODE_CLOSE_ORDER_EXIST=10039, TRADE_RETCODE_LIMIT_POSITIONS=10040, TRADE_RETCODE_REJECT_CANCEL=10041, TRADE_RETCODE_LONG_ONLY=10042, TRADE_RETCODE_SHORT_ONLY=10043, TRADE_RETCODE_CLOSE_ONLY=10044, TRADE_RETCODE_FIFO_CLOSE=10045 };

// Symbol property enums
enum ENUM_SYMBOL_INFO_INTEGER { SYMBOL_SELECT=0, SYMBOL_VISIBLE=1, SYMBOL_SESSION_DEALS=2, SYMBOL_SESSION_BUY_ORDERS=3, SYMBOL_SESSION_SELL_ORDERS=4, SYMBOL_VOLUME=5, SYMBOL_VOLUMEHIGH=6, SYMBOL_VOLUMELOW=7, SYMBOL_TIME=8, SYMBOL_TIME_MSC=9, SYMBOL_DIGITS=10, SYMBOL_SPREAD_FLOAT=11, SYMBOL_SPREAD=12, SYMBOL_TICKS_BOOKDEPTH=13, SYMBOL_TRADE_CALC_MODE=14, SYMBOL_TRADE_MODE=15, SYMBOL_START_TIME=16, SYMBOL_EXPIRATION_TIME=17, SYMBOL_TRADE_STOPS_LEVEL=18, SYMBOL_TRADE_FREEZE_LEVEL=19, SYMBOL_TRADE_EXEMODE=20, SYMBOL_SWAP_MODE=21, SYMBOL_SWAP_ROLLOVER3DAYS=22, SYMBOL_MARGIN_HEDGED_USE_LEG=23, SYMBOL_EXPIRATION_MODE=24, SYMBOL_FILLING_MODE=25, SYMBOL_ORDER_MODE=26, SYMBOL_ORDER_GTC_MODE=27, SYMBOL_OPTION_MODE=28, SYMBOL_OPTION_RIGHT=29, SYMBOL_BACKGROUND_COLOR=30, SYMBOL_CHART_MODE=31, SYMBOL_EXIST=32, SYMBOL_CUSTOM=33, SYMBOL_MARGIN_HEDGED=34, SYMBOL_BASIS=35, SYMBOL_CATEGORY=36, SYMBOL_CURRENCY_BASE=37, SYMBOL_CURRENCY_PROFIT=38, SYMBOL_CURRENCY_MARGIN=39, SYMBOL_BANK=40, SYMBOL_DESCRIPTION=41, SYMBOL_EXCHANGE=42, SYMBOL_FORMULA=43, SYMBOL_ISIN=44, SYMBOL_NAME=45, SYMBOL_PAGE=46, SYMBOL_PATH=47, SYMBOL_SECTOR=48, SYMBOL_INDUSTRY=49 };
enum ENUM_SYMBOL_INFO_DOUBLE { SYMBOL_BID=0, SYMBOL_BIDHIGH=1, SYMBOL_BIDLOW=2, SYMBOL_ASK=3, SYMBOL_ASKHIGH=4, SYMBOL_ASKLOW=5, SYMBOL_LAST=6, SYMBOL_LASTHIGH=7, SYMBOL_LASTLOW=8, SYMBOL_VOLUME_REAL=9, SYMBOL_VOLUMEHIGH_REAL=10, SYMBOL_VOLUMELOW_REAL=11, SYMBOL_OPTION_STRIKE=12, SYMBOL_POINT=13, SYMBOL_TRADE_TICK_VALUE=14, SYMBOL_TRADE_TICK_VALUE_PROFIT=15, SYMBOL_TRADE_TICK_VALUE_LOSS=16, SYMBOL_TRADE_TICK_SIZE=17, SYMBOL_TRADE_CONTRACT_SIZE=18, SYMBOL_TRADE_ACCRUED_INTEREST=19, SYMBOL_TRADE_FACE_VALUE=20, SYMBOL_TRADE_LIQUIDITY_RATE=21, SYMBOL_VOLUME_MIN=22, SYMBOL_VOLUME_MAX=23, SYMBOL_VOLUME_STEP=24, SYMBOL_VOLUME_LIMIT=25, SYMBOL_SWAP_LONG=26, SYMBOL_SWAP_SHORT=27, SYMBOL_MARGIN_INITIAL=28, SYMBOL_MARGIN_MAINTENANCE=29, SYMBOL_SESSION_VOLUME=30, SYMBOL_SESSION_TURNOVER=31, SYMBOL_SESSION_INTEREST=32, SYMBOL_SESSION_BUY_ORDERS_VOLUME=33, SYMBOL_SESSION_SELL_ORDERS_VOLUME=34, SYMBOL_SESSION_OPEN=35, SYMBOL_SESSION_CLOSE=36, SYMBOL_SESSION_AW=37, SYMBOL_SESSION_PRICE_SETTLEMENT=38, SYMBOL_SESSION_PRICE_LIMIT_MIN=39, SYMBOL_SESSION_PRICE_LIMIT_MAX=40, SYMBOL_MARGIN_HEDGED=41, SYMBOL_PRICE_CHANGE=42, SYMBOL_PRICE_VOLATILITY=43, SYMBOL_PRICE_THEORETICAL=44, SYMBOL_PRICE_GREEKS_DELTA=45, SYMBOL_PRICE_GREEKS_THETA=46, SYMBOL_PRICE_GREEKS_GAMMA=47, SYMBOL_PRICE_GREEKS_VEGA=48, SYMBOL_PRICE_GREEKS_RHO=49, SYMBOL_PRICE_GREEKS_OMEGA=50, SYMBOL_PRICE_SENSITIVITY=51 };
enum ENUM_SYMBOL_INFO_STRING { SYMBOL_CURRENCY_BASE_STR=0, SYMBOL_CURRENCY_PROFIT_STR=1, SYMBOL_CURRENCY_MARGIN_STR=2, SYMBOL_BANK_STR=3, SYMBOL_DESCRIPTION_STR=4, SYMBOL_EXCHANGE_STR=5, SYMBOL_FORMULA_STR=6, SYMBOL_ISIN_STR=7, SYMBOL_NAME_STR=8, SYMBOL_PAGE_STR=9, SYMBOL_PATH_STR=10, SYMBOL_BASIS_STR=11, SYMBOL_CATEGORY_STR=12, SYMBOL_SECTOR_STR=13, SYMBOL_INDUSTRY_STR=14 };
enum ENUM_SYMBOL_TRADE_MODE { SYMBOL_TRADE_MODE_DISABLED=0, SYMBOL_TRADE_MODE_LONGONLY=1, SYMBOL_TRADE_MODE_SHORTONLY=2, SYMBOL_TRADE_MODE_CLOSEONLY=3, SYMBOL_TRADE_MODE_FULL=4 };
enum ENUM_SYMBOL_CALC_MODE { SYMBOL_CALC_MODE_FOREX=0, SYMBOL_CALC_MODE_FOREX_NO_LEVERAGE=1, SYMBOL_CALC_MODE_FUTURES=2, SYMBOL_CALC_MODE_CFD=3, SYMBOL_CALC_MODE_CFDINDEX=4, SYMBOL_CALC_MODE_CFDLEVERAGE=5, SYMBOL_CALC_MODE_EXCH_STOCKS=6, SYMBOL_CALC_MODE_EXCH_FUTURES=7, SYMBOL_CALC_MODE_EXCH_FUTURES_FORTS=8, SYMBOL_CALC_MODE_EXCH_BONDS=9, SYMBOL_CALC_MODE_EXCH_STOCKS_MOEX=10, SYMBOL_CALC_MODE_EXCH_BONDS_MOEX=11, SYMBOL_CALC_MODE_SERV_COLLATERAL=12 };
enum ENUM_SYMBOL_TRADE_EXECUTION { SYMBOL_TRADE_EXECUTION_REQUEST=0, SYMBOL_TRADE_EXECUTION_INSTANT=1, SYMBOL_TRADE_EXECUTION_MARKET=2, SYMBOL_TRADE_EXECUTION_EXCHANGE=3 };
enum ENUM_SYMBOL_SWAP_MODE { SYMBOL_SWAP_MODE_DISABLED=0, SYMBOL_SWAP_MODE_POINTS=1, SYMBOL_SWAP_MODE_CURRENCY_SYMBOL=2, SYMBOL_SWAP_MODE_CURRENCY_MARGIN=3, SYMBOL_SWAP_MODE_CURRENCY_DEPOSIT=4, SYMBOL_SWAP_MODE_INTEREST_CURRENT=5, SYMBOL_SWAP_MODE_INTEREST_OPEN=6, SYMBOL_SWAP_MODE_REOPEN_CURRENT=7, SYMBOL_SWAP_MODE_REOPEN_BID=8 };
enum ENUM_DAY_OF_WEEK { SUNDAY=0, MONDAY=1, TUESDAY=2, WEDNESDAY=3, THURSDAY=4, FRIDAY=5, SATURDAY=6 };
enum ENUM_SYMBOL_ORDER_GTC_MODE { SYMBOL_ORDERS_GTC=0, SYMBOL_ORDERS_DAILY=1, SYMBOL_ORDERS_DAILY_NO_STOPS=2 };
enum ENUM_SYMBOL_OPTION_MODE { SYMBOL_OPTION_MODE_EUROPEAN=0, SYMBOL_OPTION_MODE_AMERICAN=1 };
enum ENUM_SYMBOL_OPTION_RIGHT { SYMBOL_OPTION_RIGHT_CALL=0, SYMBOL_OPTION_RIGHT_PUT=1 };
enum ENUM_SYMBOL_CHART_MODE { SYMBOL_CHART_MODE_BID=0, SYMBOL_CHART_MODE_LAST=1 };
enum ENUM_SYMBOL_SECTOR { SECTOR_UNDEFINED=0, SECTOR_BASIC_MATERIALS=1, SECTOR_COMMUNICATION_SERVICES=2, SECTOR_CONSUMER_CYCLICAL=3, SECTOR_CONSUMER_DEFENSIVE=4, SECTOR_CURRENCY=5, SECTOR_CURRENCY_CRYPTO=6, SECTOR_ENERGY=7, SECTOR_FINANCIAL=8, SECTOR_HEALTHCARE=9, SECTOR_INDUSTRIALS=10, SECTOR_REAL_ESTATE=11, SECTOR_TECHNOLOGY=12, SECTOR_UTILITIES=13 };
enum ENUM_SYMBOL_INDUSTRY { INDUSTRY_UNDEFINED=0, INDUSTRY_AGRICULTURAL_INPUTS=1, INDUSTRY_ALUMINIUM=2, INDUSTRY_BUILDING_MATERIALS=3, INDUSTRY_CHEMICALS=4, INDUSTRY_COKING_COAL=5, INDUSTRY_COPPER=6, INDUSTRY_GOLD=7, INDUSTRY_LUMBER_WOOD=8, INDUSTRY_INDUSTRIAL_METALS=9, INDUSTRY_PRECIOUS_METALS=10, INDUSTRY_PAPER=11, INDUSTRY_SILVER=12, INDUSTRY_SPECIALTY_CHEMICALS=13, INDUSTRY_STEEL=14, INDUSTRY_ADVERTISING=15, INDUSTRY_BROADCASTING=16, INDUSTRY_GAMING_MULTIMEDIA=17, INDUSTRY_ENTERTAINMENT=18, INDUSTRY_INTERNET_CONTENT=19, INDUSTRY_PUBLISHING=20, INDUSTRY_TELECOM=21, INDUSTRY_APPAREL_MANUFACTURING=22, INDUSTRY_APPAREL_RETAIL=23, INDUSTRY_AUTO_MANUFACTURERS=24, INDUSTRY_AUTO_PARTS=25, INDUSTRY_AUTO_DEALERSHIP=26, INDUSTRY_DEPARTMENT_STORES=27, INDUSTRY_FOOTWEAR_ACCESSORIES=28, INDUSTRY_FURNISHINGS=29, INDUSTRY_GAMBLING=30, INDUSTRY_HOME_IMPROV_RETAIL=31, INDUSTRY_INTERNET_RETAIL=32, INDUSTRY_LEISURE=33, INDUSTRY_LODGING=34, INDUSTRY_LUXURY_GOODS=35, INDUSTRY_PACKAGING_CONTAINERS=36, INDUSTRY_PERSONAL_SERVICES=37, INDUSTRY_RECREATIONAL_VEHICLES=38, INDUSTRY_RESIDENT_CONSTRUCTION=39, INDUSTRY_RESORTS_CASINOS=40, INDUSTRY_RESTAURANTS=41, INDUSTRY_SPECIALTY_RETAIL=42, INDUSTRY_TEXTILE_MANUFACTURING=43, INDUSTRY_TRAVEL_SERVICES=44, INDUSTRY_BEVERAGES_BREWERS=45, INDUSTRY_BEVERAGES_NON_ALCO=46, INDUSTRY_BEVERAGES_WINERIES=47, INDUSTRY_CONFECTIONERS=48, INDUSTRY_DISCOUNT_STORES=49, INDUSTRY_EDUCATION_TRAINIG=50, INDUSTRY_FARM_PRODUCTS=51, INDUSTRY_FOOD_DISTRIBUTION=52, INDUSTRY_GROCERY_STORES=53, INDUSTRY_HOUSEHOLD_PRODUCTS=54, INDUSTRY_PACKAGED_FOODS=55, INDUSTRY_TOBACCO=56, INDUSTRY_OIL_GAS_DRILLING=57, INDUSTRY_OIL_GAS_EP=58, INDUSTRY_OIL_GAS_EQUIPMENT=59, INDUSTRY_OIL_GAS_INTEGRATED=60, INDUSTRY_OIL_GAS_MIDSTREAM=61, INDUSTRY_OIL_GAS_REFINING=62, INDUSTRY_THERMAL_COAL=63, INDUSTRY_URANIUM=64, INDUSTRY_EXCHANGE_TRADED_FUND=65, INDUSTRY_ASSETS_MANAGEMENT=66, INDUSTRY_BANKS_DIVERSIFIED=67, INDUSTRY_BANKS_REGIONAL=68, INDUSTRY_CAPITAL_MARKETS=69, INDUSTRY_CLOSE_END_FUND_DEBT=70, INDUSTRY_CLOSE_END_FUND_EQUITY=71, INDUSTRY_CLOSE_END_FUND_FOREIGN=72, INDUSTRY_CREDIT_SERVICES=73, INDUSTRY_FINANCIAL_CONGLOMERATE=74, INDUSTRY_FINANCIAL_DATA_EXCHANGE=75, INDUSTRY_INSURANCE_BROKERS=76, INDUSTRY_INSURANCE_DIVERSIFIED=77, INDUSTRY_INSURANCE_LIFE=78, INDUSTRY_INSURANCE_PROPERTY=79, INDUSTRY_INSURANCE_REINSURANCE=80, INDUSTRY_INSURANCE_SPECIALTY=81, INDUSTRY_MORTGAGE_FINANCE=82, INDUSTRY_SHELL_COMPANIES=83, INDUSTRY_BIOTECHNOLOGY=84, INDUSTRY_DIAGNOSTICS_RESEARCH=85, INDUSTRY_DRUGS_MANUFACTURERS=86, INDUSTRY_DRUGS_MANUFACTURERS_SPEC=87, INDUSTRY_HEALTHCARE_PLANS=88, INDUSTRY_HEALTH_INFORMATION=89, INDUSTRY_MEDICAL_FACILITIES=90, INDUSTRY_MEDICAL_DEVICES=91, INDUSTRY_MEDICAL_DISTRIBUTION=92, INDUSTRY_MEDICAL_INSTRUMENTS=93, INDUSTRY_PHARM_RETAILERS=94, INDUSTRY_AEROSPACE_DEFENSE=95, INDUSTRY_AIRLINES=96, INDUSTRY_AIRPORTS_SERVICES=97, INDUSTRY_BUILDING_PRODUCTS=98, INDUSTRY_BUSINESS_EQUIPMENT=99, INDUSTRY_CONGLOMERATES=100, INDUSTRY_CONSULTING_SERVICES=101, INDUSTRY_ELECTRICAL_EQUIPMENT=102, INDUSTRY_ENGINEERING_CONSTRUCTION=103, INDUSTRY_FARM_HEAVY_MACHINERY=104, INDUSTRY_INDUSTRIAL_DISTRIBUTION=105, INDUSTRY_INFRASTRUCTURE_OPERATIONS=106, INDUSTRY_FREIGHT_LOGISTICS=107, INDUSTRY_MARINE_SHIPPING=108, INDUSTRY_METAL_FABRICATION=109, INDUSTRY_POLLUTION_CONTROL=110, INDUSTRY_RAILROADS=111, INDUSTRY_RENTAL_LEASING=112, INDUSTRY_SECURITY_PROTECTION=113, INDUSTRY_SPEALITY_BUSINESS_SERVICES=114, INDUSTRY_SPEALITY_MACHINERY=115, INDUSTRY_STUFFING_EMPLOYMENT=116, INDUSTRY_TOOLS_ACCESSORIES=117, INDUSTRY_TRUCKING=118, INDUSTRY_WASTE_MANAGEMENT=119, INDUSTRY_REAL_ESTATE_DEVELOPMENT=120, INDUSTRY_REAL_ESTATE_DIVERSIFIED=121, INDUSTRY_REAL_ESTATE_SERVICES=122, INDUSTRY_REIT_DIVERSIFIED=123, INDUSTRY_REIT_HEALTCARE=124, INDUSTRY_REIT_HOTEL_MOTEL=125, INDUSTRY_REIT_INDUSTRIAL=126, INDUSTRY_REIT_MORTAGE=127, INDUSTRY_REIT_OFFICE=128, INDUSTRY_REIT_RESIDENTAL=129, INDUSTRY_REIT_RETAIL=130, INDUSTRY_REIT_SPECIALITY=131, INDUSTRY_COMMUNICATION_EQUIPMENT=132, INDUSTRY_COMPUTER_HARDWARE=133, INDUSTRY_CONSUMER_ELECTRONICS=134, INDUSTRY_ELECTRONIC_COMPONENTS=135, INDUSTRY_ELECTRONIC_DISTRIBUTION=136, INDUSTRY_IT_SERVICES=137, INDUSTRY_SCIENTIFIC_INSTRUMENTS=138, INDUSTRY_SEMICONDUCTOR_EQUIPMENT=139, INDUSTRY_SEMICONDUCTORS=140, INDUSTRY_SOFTWARE_APPLICATION=141, INDUSTRY_SOFTWARE_INFRASTRUCTURE=142, INDUSTRY_SOLAR=143, INDUSTRY_UTILITIES_DIVERSIFIED=144, INDUSTRY_UTILITIES_POWERPRODUCERS=145, INDUSTRY_UTILITIES_RENEWABLE=146, INDUSTRY_UTILITIES_REGULATED_ELECTRIC=147, INDUSTRY_UTILITIES_REGULATED_GAS=148, INDUSTRY_UTILITIES_REGULATED_WATER=149 };

// Trade transaction type enum (for OnTradeTransaction)
enum ENUM_TRADE_TRANSACTION_TYPE { TRADE_TRANSACTION_ORDER_ADD=0, TRADE_TRANSACTION_ORDER_UPDATE=1, TRADE_TRANSACTION_ORDER_DELETE=2, TRADE_TRANSACTION_DEAL_ADD=3, TRADE_TRANSACTION_DEAL_UPDATE=4, TRADE_TRANSACTION_DEAL_DELETE=5, TRADE_TRANSACTION_HISTORY_ADD=6, TRADE_TRANSACTION_HISTORY_UPDATE=7, TRADE_TRANSACTION_HISTORY_DELETE=8, TRADE_TRANSACTION_POSITION=9, TRADE_TRANSACTION_REQUEST=10 };

// MQL program info enums
enum ENUM_MQL_INFO_INTEGER { MQL_CODEPAGE=0, MQL_PROGRAM_TYPE=1, MQL_DLLS_ALLOWED=2, MQL_TRADE_ALLOWED=3, MQL_SIGNALS_ALLOWED=4, MQL_DEBUG=5, MQL_PROFILER=6, MQL_TESTER=7, MQL_FORWARD=8, MQL_OPTIMIZATION=9, MQL_VISUAL_MODE=10, MQL_FRAME_MODE=11, MQL_LICENSE_TYPE=12, MQL_HANDLES_USED=13, MQL_MEMORY_LIMIT=14, MQL_MEMORY_USED=15 };
enum ENUM_MQL_INFO_STRING { MQL_PROGRAM_NAME=0, MQL_PROGRAM_PATH=1 };

// Chart event constants
#define CHARTEVENT_KEYDOWN 0
#define CHARTEVENT_MOUSE_MOVE 1
#define CHARTEVENT_MOUSE_WHEEL 2
#define CHARTEVENT_OBJECT_CREATE 3
#define CHARTEVENT_OBJECT_CHANGE 4
#define CHARTEVENT_OBJECT_DELETE 5
#define CHARTEVENT_CLICK 6
#define CHARTEVENT_OBJECT_CLICK 7
#define CHARTEVENT_OBJECT_DRAG 8
#define CHARTEVENT_OBJECT_ENDEDIT 9
#define CHARTEVENT_CHART_CHANGE 10
#define CHARTEVENT_CUSTOM 1000
#define CHARTEVENT_CUSTOM_LAST 65535

// Tester statistics enum
enum ENUM_STATISTICS { STAT_INITIAL_DEPOSIT=0, STAT_WITHDRAWAL=1, STAT_PROFIT=2, STAT_GROSS_PROFIT=3, STAT_GROSS_LOSS=4, STAT_MAX_PROFITTRADE=5, STAT_MAX_LOSSTRADE=6, STAT_CONPROFITMAX=7, STAT_CONPROFITMAX_TRADES=8, STAT_MAX_CONWINS=9, STAT_MAX_CONPROFIT_TRADES=10, STAT_CONLOSSMAX=11, STAT_CONLOSSMAX_TRADES=12, STAT_MAX_CONLOSSES=13, STAT_MAX_CONLOSS_TRADES=14, STAT_BALANCEMIN=15, STAT_BALANCE_DD=16, STAT_BALANCEDD_PERCENT=17, STAT_BALANCE_DDREL_PERCENT=18, STAT_BALANCE_DD_RELATIVE=19, STAT_EQUITYMIN=20, STAT_EQUITY_DD=21, STAT_EQUITYDD_PERCENT=22, STAT_EQUITY_DDREL_PERCENT=23, STAT_EQUITY_DD_RELATIVE=24, STAT_EXPECTED_PAYOFF=25, STAT_PROFIT_FACTOR=26, STAT_RECOVERY_FACTOR=27, STAT_SHARPE_RATIO=28, STAT_MIN_MARGINLEVEL=29, STAT_CUSTOM_ONTESTER=30, STAT_DEALS=31, STAT_TRADES=32, STAT_PROFIT_TRADES=33, STAT_LOSS_TRADES=34, STAT_SHORT_TRADES=35, STAT_LONG_TRADES=36, STAT_PROFIT_SHORTTRADES=37, STAT_PROFIT_LONGTRADES=38, STAT_PROFITTRADES_AVGCON=39, STAT_LOSSTRADES_AVGCON=40 };

// Signal enums
enum ENUM_SIGNAL_BASE_INTEGER { SIGNAL_BASE_DATE_PUBLISHED=0, SIGNAL_BASE_DATE_STARTED=1, SIGNAL_BASE_DATE_UPDATED=2, SIGNAL_BASE_ID=3, SIGNAL_BASE_LEVERAGE=4, SIGNAL_BASE_PIPS=5, SIGNAL_BASE_RATING=6, SIGNAL_BASE_SUBSCRIBERS=7, SIGNAL_BASE_TRADES=8, SIGNAL_BASE_TRADE_MODE=9 };
enum ENUM_SIGNAL_BASE_DOUBLE { SIGNAL_BASE_BALANCE=0, SIGNAL_BASE_EQUITY=1, SIGNAL_BASE_GAIN=2, SIGNAL_BASE_MAX_DRAWDOWN=3, SIGNAL_BASE_PRICE=4, SIGNAL_BASE_ROI=5 };
enum ENUM_SIGNAL_BASE_STRING { SIGNAL_BASE_AUTHOR_LOGIN=0, SIGNAL_BASE_BROKER=1, SIGNAL_BASE_BROKER_SERVER=2, SIGNAL_BASE_NAME=3, SIGNAL_BASE_CURRENCY=4 };
enum ENUM_SIGNAL_INFO_INTEGER { SIGNAL_INFO_CONFIRMATIONS_DISABLED=0, SIGNAL_INFO_COPY_SLTP=1, SIGNAL_INFO_DEPOSIT_PERCENT=2, SIGNAL_INFO_ID=3, SIGNAL_INFO_SUBSCRIPTION_ENABLED=4, SIGNAL_INFO_TERMS_AGREE=5 };
enum ENUM_SIGNAL_INFO_DOUBLE { SIGNAL_INFO_EQUITY_LIMIT=0, SIGNAL_INFO_SLIPPAGE=1, SIGNAL_INFO_VOLUME_PERCENT=2 };
enum ENUM_SIGNAL_INFO_STRING { SIGNAL_INFO_NAME=0 };

// Indicator line identifiers
#define MODE_MAIN 0
#define MODE_SIGNAL 1
#define MODE_PLUSDI 1
#define MODE_MINUSDI 2
#define MODE_UPPER 1
#define MODE_LOWER 2
#define MODE_GATORJAW 1
#define MODE_GATORTEETH 2
#define MODE_GATORLIPS 3
#define MODE_TENKANSEN 1
#define MODE_KIJUNSEN 2
#define MODE_SENKOUSPANA 3
#define MODE_SENKOUSPANB 4
#define MODE_CHIKOUSPAN 5
#define BASE_LINE 0
#define UPPER_LINE 1
#define LOWER_LINE 2
#define SIGNAL_LINE 1
#define UPPER_HISTOGRAM 0
#define LOWER_HISTOGRAM 2
#define UPPER_BAND 1
#define LOWER_BAND 2
#define MAIN_LINE 0
#define TENKANSEN_LINE 1
#define KIJUNSEN_LINE 2
#define SENKOUSPANA_LINE 3
#define SENKOUSPANB_LINE 4
#define CHIKOUSPAN_LINE 5
#define GATORJAW_LINE 1
#define GATORTEETH_LINE 2
#define GATORLIPS_LINE 3

// Account property enums
enum ENUM_ACCOUNT_INFO_INTEGER { ACCOUNT_LOGIN=0, ACCOUNT_TRADE_MODE=1, ACCOUNT_LEVERAGE=2, ACCOUNT_LIMIT_ORDERS=3, ACCOUNT_MARGIN_SO_MODE=4, ACCOUNT_TRADE_ALLOWED=5, ACCOUNT_TRADE_EXPERT=6, ACCOUNT_MARGIN_MODE=7, ACCOUNT_CURRENCY_DIGITS=8, ACCOUNT_FIFO_CLOSE=9 };
enum ENUM_ACCOUNT_INFO_DOUBLE { ACCOUNT_BALANCE=0, ACCOUNT_CREDIT=1, ACCOUNT_PROFIT=2, ACCOUNT_EQUITY=3, ACCOUNT_MARGIN=4, ACCOUNT_MARGIN_FREE=5, ACCOUNT_MARGIN_LEVEL=6, ACCOUNT_MARGIN_SO_CALL=7, ACCOUNT_MARGIN_SO_SO=8, ACCOUNT_MARGIN_INITIAL=9, ACCOUNT_MARGIN_MAINTENANCE=10, ACCOUNT_ASSETS=11, ACCOUNT_LIABILITIES=12, ACCOUNT_COMMISSION_BLOCKED=13 };
enum ENUM_ACCOUNT_INFO_STRING { ACCOUNT_NAME=0, ACCOUNT_SERVER=1, ACCOUNT_CURRENCY=2, ACCOUNT_COMPANY=3 };
enum ENUM_ACCOUNT_TRADE_MODE { ACCOUNT_TRADE_MODE_DEMO=0, ACCOUNT_TRADE_MODE_CONTEST=1, ACCOUNT_TRADE_MODE_REAL=2 };
enum ENUM_ACCOUNT_STOPOUT_MODE { ACCOUNT_STOPOUT_MODE_PERCENT=0, ACCOUNT_STOPOUT_MODE_MONEY=1 };
enum ENUM_ACCOUNT_MARGIN_MODE { ACCOUNT_MARGIN_MODE_RETAIL_NETTING=0, ACCOUNT_MARGIN_MODE_EXCHANGE=1, ACCOUNT_MARGIN_MODE_RETAIL_HEDGING=2 };

// Terminal property enums
enum ENUM_TERMINAL_INFO_INTEGER { TERMINAL_BUILD=0, TERMINAL_COMMUNITY_ACCOUNT=1, TERMINAL_COMMUNITY_CONNECTION=2, TERMINAL_CONNECTED=3, TERMINAL_DLLS_ALLOWED=4, TERMINAL_TRADE_ALLOWED=5, TERMINAL_EMAIL_ENABLED=6, TERMINAL_FTP_ENABLED=7, TERMINAL_NOTIFICATIONS_ENABLED=8, TERMINAL_MAXBARS=9, TERMINAL_MQID=10, TERMINAL_CODEPAGE=11, TERMINAL_CPU_CORES=12, TERMINAL_DISK_SPACE=13, TERMINAL_MEMORY_PHYSICAL=14, TERMINAL_MEMORY_TOTAL=15, TERMINAL_MEMORY_AVAILABLE=16, TERMINAL_MEMORY_USED=17, TERMINAL_SCREEN_DPI=18, TERMINAL_PING_LAST=19, TERMINAL_X64=20, TERMINAL_KEYSTATE_LEFT=21, TERMINAL_KEYSTATE_RIGHT=22, TERMINAL_KEYSTATE_TAB=23, TERMINAL_KEYSTATE_CONTROL=24, TERMINAL_KEYSTATE_DELETE=25, TERMINAL_KEYSTATE_ESCAPE=26, TERMINAL_KEYSTATE_INSERT=27, TERMINAL_KEYSTATE_PAGEDOWN=28, TERMINAL_KEYSTATE_PAGEUP=29, TERMINAL_KEYSTATE_SCRLOCK=30, TERMINAL_KEYSTATE_CAPSLOCK=31, TERMINAL_KEYSTATE_NUMLOCK=32, TERMINAL_KEYSTATE_ENTER=33, TERMINAL_VPS=34, TERMINAL_OPENCL_SUPPORT=35, TERMINAL_SCREEN_LEFT=36, TERMINAL_SCREEN_TOP=37, TERMINAL_SCREEN_WIDTH=38, TERMINAL_SCREEN_HEIGHT=39, TERMINAL_LEFT=40, TERMINAL_TOP=41, TERMINAL_RIGHT=42, TERMINAL_BOTTOM=43, TERMINAL_RETRANSMISSION=44 };
enum ENUM_TERMINAL_INFO_DOUBLE { TERMINAL_COMMUNITY_BALANCE=0, TERMINAL_RETRANSMISSION_DOUBLE=1 };
enum ENUM_TERMINAL_INFO_STRING { TERMINAL_LANGUAGE=0, TERMINAL_COMPANY=1, TERMINAL_NAME=2, TERMINAL_PATH=3, TERMINAL_DATA_PATH=4, TERMINAL_COMMONDATA_PATH=5 };

// Chart property enums
enum ENUM_CHART_PROPERTY_INTEGER { CHART_SHOW=0, CHART_IS_OBJECT=1, CHART_BRING_TO_TOP=2, CHART_CONTEXT_MENU=3, CHART_CROSSHAIR_TOOL=4, CHART_MOUSE_SCROLL=5, CHART_EVENT_MOUSE_WHEEL=6, CHART_EVENT_MOUSE_MOVE=7, CHART_EVENT_OBJECT_CREATE=8, CHART_EVENT_OBJECT_DELETE=9, CHART_MODE=10, CHART_FOREGROUND=11, CHART_SHIFT=12, CHART_AUTOSCROLL=13, CHART_KEYBOARD_CONTROL=14, CHART_QUICK_NAVIGATION=15, CHART_SCALE=16, CHART_SCALEFIX=17, CHART_SCALEFIX_11=18, CHART_SCALE_PT_PER_BAR=19, CHART_SHOW_TICKER=20, CHART_SHOW_OHLC=21, CHART_SHOW_BID_LINE=22, CHART_SHOW_ASK_LINE=23, CHART_SHOW_LAST_LINE=24, CHART_SHOW_PERIOD_SEP=25, CHART_SHOW_GRID=26, CHART_SHOW_VOLUMES=27, CHART_SHOW_OBJECT_DESCR=28, CHART_VISIBLE_BARS=29, CHART_WINDOWS_TOTAL=30, CHART_WINDOW_IS_VISIBLE=31, CHART_WINDOW_HANDLE=32, CHART_WINDOW_YDISTANCE=33, CHART_FIRST_VISIBLE_BAR=34, CHART_WIDTH_IN_BARS=35, CHART_WIDTH_IN_PIXELS=36, CHART_HEIGHT_IN_PIXELS=37, CHART_COLOR_BACKGROUND=38, CHART_COLOR_FOREGROUND=39, CHART_COLOR_GRID=40, CHART_COLOR_VOLUME=41, CHART_COLOR_CHART_UP=42, CHART_COLOR_CHART_DOWN=43, CHART_COLOR_CHART_LINE=44, CHART_COLOR_CANDLE_BULL=45, CHART_COLOR_CANDLE_BEAR=46, CHART_COLOR_BID=47, CHART_COLOR_ASK=48, CHART_COLOR_LAST=49, CHART_COLOR_STOP_LEVEL=50, CHART_SHOW_TRADE_LEVELS=51, CHART_DRAG_TRADE_LEVELS=52, CHART_SHOW_DATE_SCALE=53, CHART_SHOW_PRICE_SCALE=54, CHART_SHOW_ONE_CLICK=55, CHART_IS_MAXIMIZED=56, CHART_IS_MINIMIZED=57, CHART_IS_DOCKED=58, CHART_FLOAT_LEFT=59, CHART_FLOAT_TOP=60, CHART_FLOAT_RIGHT=61, CHART_FLOAT_BOTTOM=62 };
enum ENUM_CHART_PROPERTY_DOUBLE { CHART_SHIFT_SIZE=0, CHART_FIXED_POSITION=1, CHART_FIXED_MAX=2, CHART_FIXED_MIN=3, CHART_POINTS_PER_BAR=4, CHART_PRICE_MIN=5, CHART_PRICE_MAX=6 };
enum ENUM_CHART_PROPERTY_STRING { CHART_COMMENT=0, CHART_EXPERT_NAME=1, CHART_SCRIPT_NAME=2 };
enum ENUM_CHART_MODE { CHART_BARS=0, CHART_CANDLES=1, CHART_LINE=2 };
enum ENUM_CHART_VOLUME_MODE { CHART_VOLUME_HIDE=0, CHART_VOLUME_TICK=1, CHART_VOLUME_REAL=2 };
enum ENUM_CHART_POSITION { CHART_BEGIN=0, CHART_CURRENT_POS=1, CHART_END=2 };

// Series info enums
enum ENUM_SERIES_INFO_INTEGER { SERIES_BARS_COUNT=0, SERIES_FIRSTDATE=1, SERIES_LASTBAR_DATE=2, SERIES_SERVER_FIRSTDATE=3, SERIES_TERMINAL_FIRSTDATE=4, SERIES_SYNCHRONIZED=5 };
enum ENUM_SERIESMODE { MODE_OPEN=0, MODE_LOW=1, MODE_HIGH=2, MODE_CLOSE=3, MODE_VOLUME=4, MODE_REAL_VOLUME=5, MODE_SPREAD=6 };

// Indicator enums
enum ENUM_APPLIED_PRICE { PRICE_CLOSE=0, PRICE_OPEN=1, PRICE_HIGH=2, PRICE_LOW=3, PRICE_MEDIAN=4, PRICE_TYPICAL=5, PRICE_WEIGHTED=6 };
enum ENUM_APPLIED_VOLUME { VOLUME_TICK=0, VOLUME_REAL=1 };
enum ENUM_MA_METHOD { MODE_SMA=0, MODE_EMA=1, MODE_SMMA=2, MODE_LWMA=3 };
enum ENUM_STO_PRICE { STO_LOWHIGH=0, STO_CLOSECLOSE=1 };
enum ENUM_INDICATOR { IND_AC=0, IND_AD=1, IND_ADX=2, IND_ADXW=3, IND_ALLIGATOR=4, IND_AMA=5, IND_AO=6, IND_ATR=7, IND_BANDS=8, IND_BEARS=9, IND_BULLS=10, IND_BWMFI=11, IND_CCI=12, IND_CHAIKIN=13, IND_CUSTOM=14, IND_DEMA=15, IND_DEMARKER=16, IND_ENVELOPES=17, IND_FORCE=18, IND_FRACTALS=19, IND_FRAMA=20, IND_GATOR=21, IND_ICHIMOKU=22, IND_MACD=23, IND_MFI=24, IND_MOMENTUM=25, IND_OBV=26, IND_OSMA=27, IND_RSI=28, IND_RVI=29, IND_SAR=30, IND_STDDEV=31, IND_STOCHASTIC=32, IND_TEMA=33, IND_TRIX=34, IND_VIDYA=35, IND_VOLUMES=36, IND_WPR=37 };
enum ENUM_DATATYPE { TYPE_BOOL=0, TYPE_CHAR=1, TYPE_UCHAR=2, TYPE_SHORT=3, TYPE_USHORT=4, TYPE_COLOR=5, TYPE_INT=6, TYPE_UINT=7, TYPE_DATETIME=8, TYPE_LONG=9, TYPE_ULONG=10, TYPE_FLOAT=11, TYPE_DOUBLE=12, TYPE_STRING=13 };
enum ENUM_DRAW_TYPE { DRAW_NONE=0, DRAW_LINE=1, DRAW_SECTION=2, DRAW_HISTOGRAM=3, DRAW_HISTOGRAM2=4, DRAW_ARROW=5, DRAW_ZIGZAG=6, DRAW_FILLING=7, DRAW_BARS=8, DRAW_CANDLES=9, DRAW_COLOR_LINE=10, DRAW_COLOR_SECTION=11, DRAW_COLOR_HISTOGRAM=12, DRAW_COLOR_HISTOGRAM2=13, DRAW_COLOR_ARROW=14, DRAW_COLOR_ZIGZAG=15, DRAW_COLOR_BARS=16, DRAW_COLOR_CANDLES=17 };
enum ENUM_PLOT_PROPERTY_INTEGER { PLOT_ARROW=0, PLOT_ARROW_SHIFT=1, PLOT_DRAW_BEGIN=2, PLOT_DRAW_TYPE=3, PLOT_SHOW_DATA=4, PLOT_SHIFT=5, PLOT_LINE_STYLE=6, PLOT_LINE_WIDTH=7, PLOT_COLOR_INDEXES=8, PLOT_LINE_COLOR=9 };
enum ENUM_PLOT_PROPERTY_DOUBLE { PLOT_EMPTY_VALUE=0 };
enum ENUM_PLOT_PROPERTY_STRING { PLOT_LABEL=0 };
enum ENUM_LINE_STYLE { STYLE_SOLID=0, STYLE_DASH=1, STYLE_DOT=2, STYLE_DASHDOT=3, STYLE_DASHDOTDOT=4 };

// Object enums
enum ENUM_OBJECT { OBJ_VLINE=0, OBJ_HLINE=1, OBJ_TREND=2, OBJ_TRENDBYANGLE=3, OBJ_CYCLES=4, OBJ_ARROWED_LINE=5, OBJ_CHANNEL=6, OBJ_STDDEVCHANNEL=7, OBJ_REGRESSION=8, OBJ_PITCHFORK=9, OBJ_GANNLINE=10, OBJ_GANNFAN=11, OBJ_GANNGRID=12, OBJ_FIBO=13, OBJ_FIBOTIMES=14, OBJ_FIBOFAN=15, OBJ_FIBOARC=16, OBJ_FIBOCHANNEL=17, OBJ_EXPANSION=18, OBJ_ELLIOTWAVE5=19, OBJ_ELLIOTWAVE3=20, OBJ_RECTANGLE=21, OBJ_TRIANGLE=22, OBJ_ELLIPSE=23, OBJ_ARROW_THUMB_UP=24, OBJ_ARROW_THUMB_DOWN=25, OBJ_ARROW_UP=26, OBJ_ARROW_DOWN=27, OBJ_ARROW_STOP=28, OBJ_ARROW_CHECK=29, OBJ_ARROW_LEFT_PRICE=30, OBJ_ARROW_RIGHT_PRICE=31, OBJ_ARROW_BUY=32, OBJ_ARROW_SELL=33, OBJ_ARROW=34, OBJ_TEXT=35, OBJ_LABEL=36, OBJ_BUTTON=37, OBJ_CHART=38, OBJ_BITMAP=39, OBJ_BITMAP_LABEL=40, OBJ_EDIT=41, OBJ_EVENT=42, OBJ_RECTANGLE_LABEL=43 };
enum ENUM_OBJECT_PROPERTY_INTEGER { OBJPROP_COLOR=0, OBJPROP_STYLE=1, OBJPROP_WIDTH=2, OBJPROP_BACK=3, OBJPROP_ZORDER=4, OBJPROP_FILL=5, OBJPROP_HIDDEN=6, OBJPROP_SELECTED=7, OBJPROP_READONLY=8, OBJPROP_TYPE=9, OBJPROP_TIME=10, OBJPROP_SELECTABLE=11, OBJPROP_CREATETIME=12, OBJPROP_LEVELS=13, OBJPROP_LEVELCOLOR=14, OBJPROP_LEVELSTYLE=15, OBJPROP_LEVELWIDTH=16, OBJPROP_ALIGN=17, OBJPROP_FONTSIZE=18, OBJPROP_RAY_LEFT=19, OBJPROP_RAY_RIGHT=20, OBJPROP_RAY=21, OBJPROP_ELLIPSE=22, OBJPROP_ARROWCODE=23, OBJPROP_TIMEFRAMES=24, OBJPROP_ANCHOR=25, OBJPROP_XDISTANCE=26, OBJPROP_YDISTANCE=27, OBJPROP_DIRECTION=28, OBJPROP_DEGREE=29, OBJPROP_DRAWLINES=30, OBJPROP_STATE=31, OBJPROP_CHART_ID=32, OBJPROP_XSIZE=33, OBJPROP_YSIZE=34, OBJPROP_XOFFSET=35, OBJPROP_YOFFSET=36, OBJPROP_PERIOD=37, OBJPROP_DATE_SCALE=38, OBJPROP_PRICE_SCALE=39, OBJPROP_CHART_SCALE=40, OBJPROP_BGCOLOR=41, OBJPROP_CORNER=42, OBJPROP_BORDER_TYPE=43, OBJPROP_BORDER_COLOR=44 };
enum ENUM_OBJECT_PROPERTY_DOUBLE { OBJPROP_PRICE=0, OBJPROP_LEVELVALUE=1, OBJPROP_SCALE=2, OBJPROP_ANGLE=3, OBJPROP_DEVIATION=4 };
enum ENUM_OBJECT_PROPERTY_STRING { OBJPROP_NAME=0, OBJPROP_TEXT=1, OBJPROP_TOOLTIP=2, OBJPROP_LEVELTEXT=3, OBJPROP_FONT=4, OBJPROP_BMPFILE=5, OBJPROP_SYMBOL=6 };
enum ENUM_BORDER_TYPE { BORDER_FLAT=0, BORDER_RAISED=1, BORDER_SUNKEN=2 };
enum ENUM_ALIGN_MODE { ALIGN_LEFT=0, ALIGN_CENTER=1, ALIGN_RIGHT=2 };
enum ENUM_ANCHOR_POINT { ANCHOR_LEFT_UPPER=0, ANCHOR_LEFT=1, ANCHOR_LEFT_LOWER=2, ANCHOR_LOWER=3, ANCHOR_RIGHT_LOWER=4, ANCHOR_RIGHT=5, ANCHOR_RIGHT_UPPER=6, ANCHOR_UPPER=7, ANCHOR_CENTER=8, ANCHOR_TOP=9, ANCHOR_BOTTOM=10 };
enum ENUM_BASE_CORNER { CORNER_LEFT_UPPER=0, CORNER_LEFT_LOWER=1, CORNER_RIGHT_LOWER=2, CORNER_RIGHT_UPPER=3 };
enum ENUM_GANN_DIRECTION { GANN_UP_TREND=0, GANN_DOWN_TREND=1 };
enum ENUM_ELLIOT_WAVE_DEGREE { ELLIOTT_GRAND_SUPERCYCLE=0, ELLIOTT_SUPERCYCLE=1, ELLIOTT_CYCLE=2, ELLIOTT_PRIMARY=3, ELLIOTT_INTERMEDIATE=4, ELLIOTT_MINOR=5, ELLIOTT_MINUTE=6, ELLIOTT_MINUETTE=7, ELLIOTT_SUBMINUETTE=8 };
enum ENUM_ARROW_ANCHOR { ANCHOR_TOP_ARROW=0, ANCHOR_BOTTOM_ARROW=1 };

// File enums
enum ENUM_FILE_PROPERTY_INTEGER { FILE_EXISTS=0, FILE_CREATE_DATE=1, FILE_MODIFY_DATE=2, FILE_ACCESS_DATE=3, FILE_SIZE=4, FILE_POSITION=5, FILE_END=6, FILE_LINE_END=7, FILE_IS_COMMON=8, FILE_IS_TEXT=9, FILE_IS_BINARY=10, FILE_IS_CSV=11, FILE_IS_ANSI=12, FILE_IS_READABLE=13, FILE_IS_WRITABLE=14 };
enum ENUM_FILE_POSITION { MQL_SEEK_SET=0, MQL_SEEK_CUR=1, MQL_SEEK_END=2 };

// Copy ticks enums
enum ENUM_COPY_TICKS { COPY_TICKS_ALL=0, COPY_TICKS_INFO=1, COPY_TICKS_TRADE=2 };

// Program enums
enum ENUM_PROGRAM_TYPE { PROGRAM_SCRIPT=0, PROGRAM_EXPERT=1, PROGRAM_INDICATOR=2, PROGRAM_SERVICE=3 };
enum ENUM_LICENSE_TYPE { LICENSE_FREE=0, LICENSE_DEMO=1, LICENSE_FULL=2, LICENSE_TIME=3 };

// Init/deinit reason enums
enum ENUM_INIT_RETCODE { INIT_SUCCEEDED=0, INIT_FAILED=1, INIT_PARAMETERS_INCORRECT=2, INIT_AGENT_NOT_SUITABLE=3 };
enum ENUM_DEINIT_REASON { REASON_PROGRAM=0, REASON_REMOVE=1, REASON_RECOMPILE=2, REASON_CHARTCHANGE=3, REASON_CHARTCLOSE=4, REASON_PARAMETERS=5, REASON_ACCOUNT=6, REASON_TEMPLATE=7, REASON_INITFAILED=8, REASON_CLOSE=9 };

// Color constants
#define clrAliceBlue 0xFFF8F0
#define clrAntiqueWhite 0xD7EBFA
#define clrAqua 0xFFFF00
#define clrAquamarine 0xD4FF7F
#define clrBeige 0xDCF5F5
#define clrBisque 0xC4E4FF
#define clrBlack 0x000000
#define clrBlanchedAlmond 0xCDEBFF
#define clrBlue 0xFF0000
#define clrBlueViolet 0xE22B8A
#define clrBrown 0x2A2AA5
#define clrBurlyWood 0x87B8DE
#define clrCadetBlue 0xA09E5F
#define clrChartreuse 0x00FF7F
#define clrChocolate 0x1E69D2
#define clrCoral 0x507FFF
#define clrCornflowerBlue 0xED9564
#define clrCornsilk 0xDCF8FF
#define clrCrimson 0x3C14DC
#define clrCyan 0xFFFF00
#define clrDarkBlue 0x8B0000
#define clrDarkCyan 0x8B8B00
#define clrDarkGoldenrod 0x0B86B8
#define clrDarkGray 0xA9A9A9
#define clrDarkGreen 0x006400
#define clrDarkKhaki 0x6BB7BD
#define clrDarkMagenta 0x8B008B
#define clrDarkOliveGreen 0x2F6B55
#define clrDarkOrange 0x008CFF
#define clrDarkOrchid 0xCC3299
#define clrDarkRed 0x00008B
#define clrDarkSalmon 0x7A96E9
#define clrDarkSeaGreen 0x8BBC8F
#define clrDarkSlateBlue 0x8B3D48
#define clrDarkSlateGray 0x4F4F2F
#define clrDarkTurquoise 0xD1CE00
#define clrDarkViolet 0xD30094
#define clrDeepPink 0x9314FF
#define clrDeepSkyBlue 0xFFBF00
#define clrDimGray 0x696969
#define clrDodgerBlue 0xFF901E
#define clrFireBrick 0x2222B2
#define clrFloralWhite 0xF0FAFF
#define clrForestGreen 0x228B22
#define clrFuchsia 0xFF00FF
#define clrGainsboro 0xDCDCDC
#define clrGhostWhite 0xFFF8F8
#define clrGold 0x00D7FF
#define clrGoldenrod 0x20A5DA
#define clrGray 0x808080
#define clrGreen 0x008000
#define clrGreenYellow 0x2FFFAD
#define clrHoneydew 0xF0FFF0
#define clrHotPink 0xB469FF
#define clrIndianRed 0x5C5CCD
#define clrIndigo 0x82004B
#define clrIvory 0xF0FFFF
#define clrKhaki 0x8CE6F0
#define clrLavender 0xFAE6E6
#define clrLavenderBlush 0xF5F0FF
#define clrLawnGreen 0x00FC7C
#define clrLemonChiffon 0xCDFAFF
#define clrLightBlue 0xE6D8AD
#define clrLightCoral 0x8080F0
#define clrLightCyan 0xFFFFE0
#define clrLightGoldenrod 0xD2FAFA
#define clrLightGray 0xD3D3D3
#define clrLightGreen 0x90EE90
#define clrLightPink 0xC1B6FF
#define clrLightSalmon 0x7AA0FF
#define clrLightSeaGreen 0xAAB220
#define clrLightSkyBlue 0xFACE87
#define clrLightSlateGray 0x998877
#define clrLightSteelBlue 0xDEC4B0
#define clrLightYellow 0xE0FFFF
#define clrLime 0x00FF00
#define clrLimeGreen 0x32CD32
#define clrLinen 0xE6F0FA
#define clrMagenta 0xFF00FF
#define clrMaroon 0x000080
#define clrMediumAquamarine 0xAACD66
#define clrMediumBlue 0xCD0000
#define clrMediumOrchid 0xD355BA
#define clrMediumPurple 0xDB7093
#define clrMediumSeaGreen 0x71B33C
#define clrMediumSlateBlue 0xEE687B
#define clrMediumSpringGreen 0x9AFA00
#define clrMediumTurquoise 0xCCD148
#define clrMediumVioletRed 0x8515C7
#define clrMidnightBlue 0x701919
#define clrMintCream 0xFAFFF5
#define clrMistyRose 0xE1E4FF
#define clrMoccasin 0xB5E4FF
#define clrNavajoWhite 0xADDEFF
#define clrNavy 0x800000
#define clrOldLace 0xE6F5FD
#define clrOlive 0x008080
#define clrOliveDrab 0x238E6B
#define clrOrange 0x00A5FF
#define clrOrangeRed 0x0045FF
#define clrOrchid 0xD670DA
#define clrPaleGoldenrod 0xAAE8EE
#define clrPaleGreen 0x98FB98
#define clrPaleTurquoise 0xEEEEAF
#define clrPaleVioletRed 0x9370DB
#define clrPapayaWhip 0xD5EFFF
#define clrPeachPuff 0xB9DAFF
#define clrPeru 0x3F85CD
#define clrPink 0xCBC0FF
#define clrPlum 0xDDA0DD
#define clrPowderBlue 0xE6E0B0
#define clrPurple 0x800080
#define clrRed 0x0000FF
#define clrRosyBrown 0x8F8FBC
#define clrRoyalBlue 0xE16941
#define clrSaddleBrown 0x13458B
#define clrSalmon 0x7280FA
#define clrSandyBrown 0x60A4F4
#define clrSeaGreen 0x578B2E
#define clrSeashell 0xEEF5FF
#define clrSienna 0x2D52A0
#define clrSilver 0xC0C0C0
#define clrSkyBlue 0xEBCE87
#define clrSlateBlue 0xCD5A6A
#define clrSlateGray 0x908070
#define clrSnow 0xFAFAFF
#define clrSpringGreen 0x7FFF00
#define clrSteelBlue 0xB48246
#define clrTan 0x8CB4D2
#define clrTeal 0x808000
#define clrThistle 0xD8BFD8
#define clrTomato 0x4763FF
#define clrTurquoise 0xD0E040
#define clrViolet 0xEE82EE
#define clrWheat 0xB3DEF5
#define clrWhite 0xFFFFFF
#define clrWhiteSmoke 0xF5F5F5
#define clrYellow 0x00FFFF
#define clrYellowGreen 0x32CD9A

// Mathematical constants
#define M_PI 3.14159265358979323846
#define M_E 2.71828182845904523536
#define M_LOG2E 1.44269504088896340736
#define M_LOG10E 0.434294481903251827651
#define M_LN2 0.693147180559945309417
#define M_LN10 2.30258509299404568402
#define M_PI_2 1.57079632679489661923
#define M_PI_4 0.785398163397448309616
#define M_1_PI 0.318309886183790671538
#define M_2_PI 0.636619772367581343076
#define M_2_SQRTPI 1.12837916709551257390
#define M_SQRT2 1.41421356237309504880
#define M_SQRT1_2 0.707106781186547524401

// Limits
#define INT_MAX 2147483647
#define INT_MIN (-2147483647-1)
#define UINT_MAX 4294967295
#define LONG_MAX 9223372036854775807LL
#define LONG_MIN (-9223372036854775807LL-1)
#define ULONG_MAX 18446744073709551615ULL
#define DBL_MAX 1.7976931348623158e+308
#define DBL_MIN 2.2250738585072014e-308
#define DBL_EPSILON 2.2204460492503131e-016
#define FLT_MAX 3.402823466e+38f
#define FLT_MIN 1.175494351e-38f
#define FLT_EPSILON 1.192092896e-07f

// Additional MQL5 structures
struct MqlTick { datetime time; double bid; double ask; double last; ulong volume; long time_msc; uint flags; double volume_real; };
struct MqlRates { datetime time; double open; double high; double low; double close; long tick_volume; int spread; long real_volume; };
struct MqlBookInfo { ENUM_BOOK_TYPE type; double price; long volume; double volume_real; };
struct MqlTradeCheckResult { uint retcode; double balance; double equity; double profit; double margin; double margin_free; double margin_level; string comment; };
struct MqlTradeTransaction { ulong deal; ulong order; string symbol; ENUM_TRADE_TRANSACTION_TYPE type; ENUM_ORDER_TYPE order_type; ENUM_ORDER_STATE order_state; ENUM_DEAL_TYPE deal_type; ENUM_ORDER_TYPE_TIME time_type; datetime time_expiration; double price; double price_trigger; double price_sl; double price_tp; double volume; ulong position; ulong position_by; };
struct MqlParam { ENUM_DATATYPE type; long integer_value; double double_value; string string_value; };
struct MqlCalendarValue { ulong id; ulong event_id; datetime time; datetime period; int revision; long actual_value; long prev_value; long revised_prev_value; long forecast_value; int impact_type; };
struct MqlCalendarEvent { ulong id; ENUM_CALENDAR_EVENT_TYPE type; ENUM_CALENDAR_EVENT_SECTOR sector; ENUM_CALENDAR_EVENT_FREQUENCY frequency; ENUM_CALENDAR_EVENT_TIMEMODE time_mode; ulong country_id; ENUM_CALENDAR_EVENT_UNIT unit; ENUM_CALENDAR_EVENT_IMPORTANCE importance; ENUM_CALENDAR_EVENT_MULTIPLIER multiplier; uint digits; string source_url; string event_code; string name; };
struct MqlCalendarCountry { ulong id; string name; string code; string currency; string currency_symbol; string url_name; };

// Book type enum
enum ENUM_BOOK_TYPE { BOOK_TYPE_SELL=1, BOOK_TYPE_BUY=2, BOOK_TYPE_SELL_MARKET=3, BOOK_TYPE_BUY_MARKET=4 };

// Calendar enums
enum ENUM_CALENDAR_EVENT_TYPE { CALENDAR_TYPE_EVENT=0, CALENDAR_TYPE_INDICATOR=1, CALENDAR_TYPE_HOLIDAY=2 };
enum ENUM_CALENDAR_EVENT_SECTOR { CALENDAR_SECTOR_NONE=0, CALENDAR_SECTOR_MARKET=1, CALENDAR_SECTOR_GDP=2, CALENDAR_SECTOR_JOBS=3, CALENDAR_SECTOR_PRICES=4, CALENDAR_SECTOR_MONEY=5, CALENDAR_SECTOR_TRADE=6, CALENDAR_SECTOR_GOVERNMENT=7, CALENDAR_SECTOR_BUSINESS=8, CALENDAR_SECTOR_CONSUMER=9, CALENDAR_SECTOR_HOUSING=10, CALENDAR_SECTOR_TAXES=11, CALENDAR_SECTOR_HOLIDAYS=12 };
enum ENUM_CALENDAR_EVENT_FREQUENCY { CALENDAR_FREQUENCY_NONE=0, CALENDAR_FREQUENCY_WEEK=1, CALENDAR_FREQUENCY_MONTH=2, CALENDAR_FREQUENCY_QUARTER=3, CALENDAR_FREQUENCY_YEAR=4, CALENDAR_FREQUENCY_DAY=5 };
enum ENUM_CALENDAR_EVENT_TIMEMODE { CALENDAR_TIMEMODE_DATETIME=0, CALENDAR_TIMEMODE_DATE=1, CALENDAR_TIMEMODE_NOTIME=2, CALENDAR_TIMEMODE_TENTATIVE=3 };
enum ENUM_CALENDAR_EVENT_UNIT { CALENDAR_UNIT_NONE=0, CALENDAR_UNIT_PERCENT=1, CALENDAR_UNIT_CURRENCY=2, CALENDAR_UNIT_HOUR=3, CALENDAR_UNIT_JOB=4, CALENDAR_UNIT_RIG=5, CALENDAR_UNIT_USD=6, CALENDAR_UNIT_PEOPLE=7, CALENDAR_UNIT_MORTGAGE=8, CALENDAR_UNIT_VOTE=9, CALENDAR_UNIT_BARREL=10, CALENDAR_UNIT_CUBICFEET=11, CALENDAR_UNIT_POSITION=12, CALENDAR_UNIT_BUILDING=13 };
enum ENUM_CALENDAR_EVENT_IMPORTANCE { CALENDAR_IMPORTANCE_NONE=0, CALENDAR_IMPORTANCE_LOW=1, CALENDAR_IMPORTANCE_MODERATE=2, CALENDAR_IMPORTANCE_HIGH=3 };
enum ENUM_CALENDAR_EVENT_MULTIPLIER { CALENDAR_MULTIPLIER_NONE=0, CALENDAR_MULTIPLIER_THOUSANDS=1, CALENDAR_MULTIPLIER_MILLIONS=2, CALENDAR_MULTIPLIER_BILLIONS=3, CALENDAR_MULTIPLIER_TRILLIONS=4 };

// Tick flags
#define TICK_FLAG_BID 0x02
#define TICK_FLAG_ASK 0x04
#define TICK_FLAG_LAST 0x08
#define TICK_FLAG_VOLUME 0x10
#define TICK_FLAG_BUY 0x20
#define TICK_FLAG_SELL 0x40

// File flags
#define FILE_READ 1
#define FILE_WRITE 2
#define FILE_BIN 4
#define FILE_CSV 8
#define FILE_TXT 16
#define FILE_ANSI 32
#define FILE_UNICODE 64
#define FILE_SHARE_READ 128
#define FILE_SHARE_WRITE 256
#define FILE_REWRITE 512
#define FILE_COMMON 4096

// Pointer types
#define POINTER_INVALID 0
#define POINTER_DYNAMIC 1
#define POINTER_AUTOMATIC 2

// ArrayCopy direction
#define WHOLE_ARRAY -1

// Symbol and period functions
string Symbol();
ENUM_TIMEFRAMES Period();
string periodName(int p=0);
int Digits();
double Point();

// Predefined variable aliases (MQL5 style)
#define _Symbol Symbol()
#define _Period Period()
#define _Digits Digits()
#define _Point Point()
#define _LastError GetLastError()
#define _StopFlag IsStopped()
#define _UninitReason UninitializeReason()

// Time functions
datetime TimeCurrent();
datetime TimeCurrent(MqlDateTime& dt_struct);
datetime TimeLocal();
datetime TimeLocal(MqlDateTime& dt_struct);
datetime TimeGMT();
datetime TimeGMT(MqlDateTime& dt_struct);
datetime TimeDaylightSavings();
datetime TimeGMTOffset();
datetime TimeTradeServer();
void TimeToStruct(datetime dt, MqlDateTime& dt_struct);
datetime StructToTime(MqlDateTime& dt_struct);
int Day();
int DayOfWeek();
int DayOfYear();
int Hour();
int Minute();
int Month();
int Seconds();
int TimeDay(datetime date);
int TimeDayOfWeek(datetime date);
int TimeDayOfYear(datetime date);
int TimeHour(datetime date);
int TimeMinute(datetime date);
int TimeMonth(datetime date);
int TimeSeconds(datetime date);
int TimeYear(datetime date);
int Year();

// Print functions
void Print(...);
void PrintFormat(string format, ...);
void Alert(...);
void Comment(...);

// Error functions
int GetLastError();
void ResetLastError();
string ErrorDescription(int error_code);

// System functions
int GetTickCount();
ulong GetTickCount64();
ulong GetMicrosecondCount();
void Sleep(int milliseconds);
bool IsStopped();
int UninitializeReason();
bool MQLInfoInteger(int property_id);
string MQLInfoString(int property_id);
int TerminalInfoInteger(int property_id);
double TerminalInfoDouble(int property_id);
string TerminalInfoString(int property_id);

// Checkup functions
bool TerminalClose(int ret_code);
bool RefreshRates();

// Account functions
long AccountInfoInteger(ENUM_ACCOUNT_INFO_INTEGER property_id);
double AccountInfoDouble(ENUM_ACCOUNT_INFO_DOUBLE property_id);
string AccountInfoString(ENUM_ACCOUNT_INFO_STRING property_id);
double AccountBalance();
double AccountCredit();
string AccountCompany();
string AccountCurrency();
double AccountEquity();
double AccountFreeMargin();
double AccountFreeMarginCheck(string symbol, int cmd, double volume);
double AccountFreeMarginMode();
int AccountLeverage();
double AccountMargin();
string AccountName();
int AccountNumber();
double AccountProfit();
string AccountServer();
int AccountStopoutLevel();
int AccountStopoutMode();

// Symbol functions
long SymbolInfoInteger(string symbol, ENUM_SYMBOL_INFO_INTEGER property_id);
double SymbolInfoDouble(string symbol, ENUM_SYMBOL_INFO_DOUBLE property_id);
string SymbolInfoString(string symbol, ENUM_SYMBOL_INFO_STRING property_id);
bool SymbolInfoTick(string symbol, MqlTick& tick);
bool SymbolInfoMarginRate(string symbol, ENUM_ORDER_TYPE order_type, double& initial_margin_rate, double& maintenance_margin_rate);
int SymbolsTotal(bool selected);
string SymbolName(int pos, bool selected);
bool SymbolSelect(string name, bool select);
bool SymbolIsSynchronized(string name);
double MarketInfo(string symbol, int type);
int SymbolInfoSessionQuote(string name, ENUM_DAY_OF_WEEK day_of_week, uint session_index, datetime& from, datetime& to);
int SymbolInfoSessionTrade(string name, ENUM_DAY_OF_WEEK day_of_week, uint session_index, datetime& from, datetime& to);

// MQL5 Trading functions
bool OrderSend(const MqlTradeRequest &request, MqlTradeResult &result);
bool OrderSendAsync(const MqlTradeRequest &request, MqlTradeResult &result);
bool OrderCheck(const MqlTradeRequest &request, MqlTradeCheckResult &result);
bool PositionSelect(string symbol);
bool PositionSelectByTicket(ulong ticket);
int PositionsTotal();
string PositionGetSymbol(int index);
ulong PositionGetTicket(int index);
long PositionGetInteger(ENUM_POSITION_PROPERTY_INTEGER property_id);
double PositionGetDouble(ENUM_POSITION_PROPERTY_DOUBLE property_id);
string PositionGetString(ENUM_POSITION_PROPERTY_STRING property_id);
int OrdersTotal();
ulong OrderGetTicket(int index);
bool OrderSelect(ulong ticket);
long OrderGetInteger(ENUM_ORDER_PROPERTY_INTEGER property_id);
double OrderGetDouble(ENUM_ORDER_PROPERTY_DOUBLE property_id);
string OrderGetString(ENUM_ORDER_PROPERTY_STRING property_id);
bool HistorySelect(datetime from_date, datetime to_date);
bool HistorySelectByPosition(long position_id);
int HistoryOrdersTotal();
ulong HistoryOrderGetTicket(int index);
bool HistoryOrderSelect(ulong ticket);
long HistoryOrderGetInteger(ulong ticket_number, ENUM_ORDER_PROPERTY_INTEGER property_id);
double HistoryOrderGetDouble(ulong ticket_number, ENUM_ORDER_PROPERTY_DOUBLE property_id);
string HistoryOrderGetString(ulong ticket_number, ENUM_ORDER_PROPERTY_STRING property_id);
int HistoryDealsTotal();
ulong HistoryDealGetTicket(int index);
bool HistoryDealSelect(ulong ticket);
long HistoryDealGetInteger(ulong ticket_number, ENUM_DEAL_PROPERTY_INTEGER property_id);
double HistoryDealGetDouble(ulong ticket_number, ENUM_DEAL_PROPERTY_DOUBLE property_id);
string HistoryDealGetString(ulong ticket_number, ENUM_DEAL_PROPERTY_STRING property_id);

// MQL4 Trading functions (legacy compatibility)
int OrderSend(string symbol, int cmd, double volume, double price, int slippage, double stoploss, double takeprofit, string comment = "", int magic = 0, datetime expiration = 0, color arrow_color = clrNONE);
bool OrderModify(int ticket, double price, double stoploss, double takeprofit, datetime expiration, color arrow_color = clrNONE);
bool OrderClose(int ticket, double lots, double price, int slippage, color arrow_color = clrNONE);
bool OrderCloseBy(int ticket, int opposite, color arrow_color = clrNONE);
bool OrderDelete(int ticket, color arrow_color = clrNONE);
bool OrderSelect(int index, int select, int pool = MODE_TRADES);
int OrderType();
int OrderTicket();
double OrderOpenPrice();
double OrderClosePrice();
double OrderLots();
double OrderProfit();
double OrderStopLoss();
double OrderTakeProfit();
double OrderCommission();
double OrderSwap();
datetime OrderOpenTime();
datetime OrderCloseTime();
datetime OrderExpiration();
int OrderMagicNumber();
string OrderSymbol();
string OrderComment();

// MQL4 Order pool constants
#define MODE_TRADES 0
#define MODE_HISTORY 1
#define SELECT_BY_POS 0
#define SELECT_BY_TICKET 1

// MQL4 Order type constants
#define OP_BUY 0
#define OP_SELL 1
#define OP_BUYLIMIT 2
#define OP_SELLLIMIT 3
#define OP_BUYSTOP 4
#define OP_SELLSTOP 5

// Series functions
int Bars(string symbol, ENUM_TIMEFRAMES timeframe);
int Bars(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, datetime stop_time);
int iBars(string symbol, ENUM_TIMEFRAMES timeframe);
int iBarShift(string symbol, ENUM_TIMEFRAMES timeframe, datetime time, bool exact = false);
long SeriesInfoInteger(string symbol, ENUM_TIMEFRAMES timeframe, ENUM_SERIES_INFO_INTEGER prop_id);
// CopyRates - 3 overloads
int CopyRates(string symbol, ENUM_TIMEFRAMES timeframe, int start_pos, int count, MqlRates rates_array[]);
int CopyRates(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, int count, MqlRates rates_array[]);
int CopyRates(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, datetime stop_time, MqlRates rates_array[]);

// CopyTime - 3 overloads
int CopyTime(string symbol, ENUM_TIMEFRAMES timeframe, int start_pos, int count, datetime time_array[]);
int CopyTime(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, int count, datetime time_array[]);
int CopyTime(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, datetime stop_time, datetime time_array[]);

// CopyOpen - 3 overloads
int CopyOpen(string symbol, ENUM_TIMEFRAMES timeframe, int start_pos, int count, double open_array[]);
int CopyOpen(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, int count, double open_array[]);
int CopyOpen(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, datetime stop_time, double open_array[]);

// CopyHigh - 3 overloads
int CopyHigh(string symbol, ENUM_TIMEFRAMES timeframe, int start_pos, int count, double high_array[]);
int CopyHigh(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, int count, double high_array[]);
int CopyHigh(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, datetime stop_time, double high_array[]);

// CopyLow - 3 overloads
int CopyLow(string symbol, ENUM_TIMEFRAMES timeframe, int start_pos, int count, double low_array[]);
int CopyLow(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, int count, double low_array[]);
int CopyLow(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, datetime stop_time, double low_array[]);

// CopyClose - 3 overloads
int CopyClose(string symbol, ENUM_TIMEFRAMES timeframe, int start_pos, int count, double close_array[]);
int CopyClose(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, int count, double close_array[]);
int CopyClose(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, datetime stop_time, double close_array[]);

// CopyTickVolume - 3 overloads
int CopyTickVolume(string symbol, ENUM_TIMEFRAMES timeframe, int start_pos, int count, long volume_array[]);
int CopyTickVolume(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, int count, long volume_array[]);
int CopyTickVolume(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, datetime stop_time, long volume_array[]);

// CopyRealVolume - 3 overloads
int CopyRealVolume(string symbol, ENUM_TIMEFRAMES timeframe, int start_pos, int count, long volume_array[]);
int CopyRealVolume(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, int count, long volume_array[]);
int CopyRealVolume(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, datetime stop_time, long volume_array[]);

// CopySpread - 3 overloads
int CopySpread(string symbol, ENUM_TIMEFRAMES timeframe, int start_pos, int count, int spread_array[]);
int CopySpread(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, int count, int spread_array[]);
int CopySpread(string symbol, ENUM_TIMEFRAMES timeframe, datetime start_time, datetime stop_time, int spread_array[]);

// CopyBuffer - 3 overloads
int CopyBuffer(int indicator_handle, int buffer_num, int start_pos, int count, double buffer[]);
int CopyBuffer(int indicator_handle, int buffer_num, datetime start_time, int count, double buffer[]);
int CopyBuffer(int indicator_handle, int buffer_num, datetime start_time, datetime stop_time, double buffer[]);

int CopyTicks(string symbol, MqlTick ticks_array[], uint flags = COPY_TICKS_ALL, ulong from = 0, uint count = 0);
int CopyTicksRange(string symbol, MqlTick ticks_array[], uint flags, ulong from_msc, ulong to_msc);

// Timeseries access
double iOpen(string symbol, ENUM_TIMEFRAMES timeframe, int shift);
double iHigh(string symbol, ENUM_TIMEFRAMES timeframe, int shift);
double iLow(string symbol, ENUM_TIMEFRAMES timeframe, int shift);
double iClose(string symbol, ENUM_TIMEFRAMES timeframe, int shift);
long iVolume(string symbol, ENUM_TIMEFRAMES timeframe, int shift);
datetime iTime(string symbol, ENUM_TIMEFRAMES timeframe, int shift);
int iHighest(string symbol, ENUM_TIMEFRAMES timeframe, int type, int count = WHOLE_ARRAY, int start = 0);
int iLowest(string symbol, ENUM_TIMEFRAMES timeframe, int type, int count = WHOLE_ARRAY, int start = 0);

// Array functions
template<typename T> int ArraySize(const T array[]);
template<typename T> int ArrayResize(T array[], int new_size, int reserve_size = 0);
template<typename T> void ArrayFree(T array[]);
template<typename T> bool ArraySetAsSeries(T array[], bool flag);
template<typename T> bool ArrayGetAsSeries(const T array[]);
template<typename T> int ArrayInitialize(T array[], T value);
template<typename T> int ArrayCopy(T dst_array[], const T src_array[], int dst_start = 0, int src_start = 0, int count = WHOLE_ARRAY);
template<typename T> int ArrayMaximum(const T array[], int start = 0, int count = WHOLE_ARRAY);
template<typename T> int ArrayMinimum(const T array[], int start = 0, int count = WHOLE_ARRAY);
template<typename T> bool ArraySort(T array[]);
template<typename T> bool ArrayReverse(T array[], int start = 0, int count = WHOLE_ARRAY);
template<typename T> int ArrayBsearch(const T array[], T value, int start = 0, int count = WHOLE_ARRAY);
template<typename T> int ArrayRange(const T array[], int rank_index);
template<typename T> void ArrayPrint(const T array[], int digits = 16, const string separator = " ");
template<typename T> bool ArrayIsDynamic(const T array[]);
template<typename T> bool ArrayIsSeries(const T array[]);
template<typename T> void ArraySwap(T array1[], T array2[]);

// String functions
int StringLen(string str);
string StringSubstr(string str, int start_pos, int length = -1);
int StringFind(string str, string match_substring, int start_pos = 0);
int StringReplace(string& str, const string find, const string replacement);
string StringTrimLeft(string str);
string StringTrimRight(string str);
bool StringToLower(string& str);
bool StringToUpper(string& str);
int StringCompare(const string& str1, const string& str2, bool case_sensitive = true);
int StringSplit(const string str, const ushort separator, string result[]);
string StringFormat(string format, ...);
string CharToString(uchar char_code);
int StringToCharArray(string text, uchar array[], int start = 0, int count = -1, uint codepage = 0);
string CharArrayToString(uchar array[], int start = 0, int count = -1, uint codepage = 0);
string ShortToString(ushort symbol_code);
int StringToShortArray(string text, ushort array[], int start = 0, int count = -1);
string ShortArrayToString(ushort array[], int start = 0, int count = -1);
bool StringConcatenate(string& string_var, ...);
int StringGetCharacter(string str, int pos);
bool StringSetCharacter(string& str, int pos, ushort character);
string StringAdd(const string& str1, const string& str2);
bool StringInit(string& string_var, int new_len = 0, ushort character = 0);
bool StringFill(string& string_var, ushort character);
int StringBufferLen(string str);
bool StringReserve(string& string_var, uint new_capacity);
bool StringSetLength(string& string_var, uint new_length);

// Conversion functions
string IntegerToString(long number, int str_len = 0, ushort fill_symbol = ' ');
string DoubleToString(double value, int digits = 8);
string TimeToString(datetime value, int mode = 19);
string ColorToString(color color_value, bool color_name = false);
string EnumToString(int value);
long StringToInteger(string value);
double StringToDouble(string value);
datetime StringToTime(string value);
color StringToColor(string value);
double NormalizeDouble(double value, int digits);
bool CharArrayToStruct(void* struct_object, const uchar array[], uint start_pos = 0);
bool StructToCharArray(const void* struct_object, uchar array[], uint start_pos = 0);

// Math functions
double MathAbs(double value);
double MathArccos(double value);
double MathArcsin(double value);
double MathArctan(double value);
double MathCeil(double value);
double MathCos(double value);
double MathExp(double value);
double MathFloor(double value);
double MathLog(double value);
double MathLog10(double value);
double MathMax(double value1, double value2);
double MathMin(double value1, double value2);
double MathMod(double value1, double value2);
double MathPow(double base, double exponent);
double MathRand();
double MathRound(double value);
double MathSin(double value);
double MathSqrt(double value);
double MathTan(double value);
void MathSrand(int seed);
bool MathIsValidNumber(double number);
double MathExpm1(double value);
double MathLog1p(double value);
double MathArccosh(double value);
double MathArcsinh(double value);
double MathArctanh(double value);
double MathCosh(double value);
double MathSinh(double value);
double MathTanh(double value);
double MathSwap(double value);
int MathSwap(int value);
short MathSwap(short value);
ushort MathSwap(ushort value);

// Compatibility math functions
double fabs(double value);
double acos(double value);
double asin(double value);
double atan(double value);
double ceil(double value);
double cos(double value);
double exp(double value);
double floor(double value);
double log(double value);
double log10(double value);
double fmax(double value1, double value2);
double fmin(double value1, double value2);
double fmod(double value1, double value2);
double pow(double base, double exponent);
int rand();
double round(double value);
double sin(double value);
double sqrt(double value);
double tan(double value);
void srand(int seed);

// File functions
int FileOpen(string file_name, int open_flags, short delimiter = '\t', uint codepage = 0);
void FileClose(int file_handle);
uint FileReadInteger(int file_handle, int size = 4);
double FileReadDouble(int file_handle);
float FileReadFloat(int file_handle);
long FileReadLong(int file_handle);
int FileReadNumber(int file_handle);
string FileReadString(int file_handle, int length = -1);
uint FileReadArray(int file_handle, void* array, int start = 0, int count = WHOLE_ARRAY);
bool FileReadStruct(int file_handle, void* struct_object, int size = -1);
uint FileWriteInteger(int file_handle, int value, int size = 4);
uint FileWriteDouble(int file_handle, double value);
uint FileWriteFloat(int file_handle, float value);
uint FileWriteLong(int file_handle, long value);
uint FileWriteString(int file_handle, string value, int length = -1);
uint FileWriteArray(int file_handle, const void* array, int start = 0, int count = WHOLE_ARRAY);
uint FileWriteStruct(int file_handle, const void* struct_object, int size = -1);
uint FileWrite(int file_handle, ...);
bool FileSeek(int file_handle, long offset, ENUM_FILE_POSITION origin);
void FileFlush(int file_handle);
bool FileIsExist(string file_name, int common_flag = 0);
bool FileDelete(string file_name, int common_flag = 0);
bool FileCopy(string src_file_name, int common_flag, string dst_file_name, int mode_flags);
bool FileMove(string src_file_name, int common_flag, string dst_file_name, int mode_flags);
ulong FileSize(int file_handle);
ulong FileTell(int file_handle);
bool FileIsEnding(int file_handle);
bool FileIsLineEnding(int file_handle);
bool FolderCreate(string folder_name, int common_flag = 0);
bool FolderDelete(string folder_name, int common_flag = 0);
bool FolderClean(string folder_name, int common_flag = 0);
string FileFindFirst(string file_filter, string& returned_filename, int common_flag = 0);
bool FileFindNext(long search_handle, string& returned_filename);
void FileFindClose(long search_handle);
long FileGetInteger(int file_handle, ENUM_FILE_PROPERTY_INTEGER property_id);

// Object functions
bool ObjectCreate(long chart_id, string name, ENUM_OBJECT type, int sub_window, datetime time1, double price1, datetime time2 = 0, double price2 = 0, datetime time3 = 0, double price3 = 0);
string ObjectName(long chart_id, int pos, int sub_window = -1, int type = -1);
bool ObjectDelete(long chart_id, string name);
int ObjectsDeleteAll(long chart_id, int sub_window = EMPTY, int type = EMPTY);
int ObjectsTotal(long chart_id, int sub_window = -1, int type = -1);
bool ObjectSetDouble(long chart_id, string name, ENUM_OBJECT_PROPERTY_DOUBLE prop_id, double prop_value);
bool ObjectSetDouble(long chart_id, string name, ENUM_OBJECT_PROPERTY_DOUBLE prop_id, int prop_modifier, double prop_value);
bool ObjectSetInteger(long chart_id, string name, ENUM_OBJECT_PROPERTY_INTEGER prop_id, long prop_value);
bool ObjectSetInteger(long chart_id, string name, ENUM_OBJECT_PROPERTY_INTEGER prop_id, int prop_modifier, long prop_value);
bool ObjectSetString(long chart_id, string name, ENUM_OBJECT_PROPERTY_STRING prop_id, string prop_value);
bool ObjectSetString(long chart_id, string name, ENUM_OBJECT_PROPERTY_STRING prop_id, int prop_modifier, string prop_value);
// ObjectGetDouble - 2 overloads
double ObjectGetDouble(long chart_id, string name, ENUM_OBJECT_PROPERTY_DOUBLE prop_id, int prop_modifier = 0);
bool ObjectGetDouble(long chart_id, string name, ENUM_OBJECT_PROPERTY_DOUBLE prop_id, int prop_modifier, double& double_var);

// ObjectGetInteger - 2 overloads
long ObjectGetInteger(long chart_id, string name, ENUM_OBJECT_PROPERTY_INTEGER prop_id, int prop_modifier = 0);
bool ObjectGetInteger(long chart_id, string name, ENUM_OBJECT_PROPERTY_INTEGER prop_id, int prop_modifier, long& long_var);

// ObjectGetString - 2 overloads
string ObjectGetString(long chart_id, string name, ENUM_OBJECT_PROPERTY_STRING prop_id, int prop_modifier = 0);
bool ObjectGetString(long chart_id, string name, ENUM_OBJECT_PROPERTY_STRING prop_id, int prop_modifier, string& string_var);
bool ObjectMove(long chart_id, string name, int point_index, datetime time, double price);
int ObjectFind(long chart_id, string name);
datetime ObjectGetTimeByValue(long chart_id, string name, double value, int line_id = 0);
double ObjectGetValueByTime(long chart_id, string name, datetime time, int line_id = 0);
ENUM_OBJECT ObjectType(string name);
string ObjectDescription(string name);
bool ObjectGet(string name, int prop_id);
bool ObjectSet(string name, int prop_id, double value);

// Chart functions
long ChartOpen(string symbol, ENUM_TIMEFRAMES period);
bool ChartClose(long chart_id = 0);
long ChartFirst();
long ChartNext(long chart_id);
string ChartSymbol(long chart_id = 0);
ENUM_TIMEFRAMES ChartPeriod(long chart_id = 0);
void ChartRedraw(long chart_id = 0);
bool ChartSetDouble(long chart_id, ENUM_CHART_PROPERTY_DOUBLE prop_id, double value);
bool ChartSetInteger(long chart_id, ENUM_CHART_PROPERTY_INTEGER prop_id, long value);
bool ChartSetString(long chart_id, ENUM_CHART_PROPERTY_STRING prop_id, string value);
bool ChartSetSymbolPeriod(long chart_id, string symbol, ENUM_TIMEFRAMES period);
// ChartGetDouble - 2 overloads
double ChartGetDouble(long chart_id, ENUM_CHART_PROPERTY_DOUBLE prop_id, int sub_window = 0);
bool ChartGetDouble(long chart_id, ENUM_CHART_PROPERTY_DOUBLE prop_id, int sub_window, double& double_var);

// ChartGetInteger - 2 overloads
long ChartGetInteger(long chart_id, ENUM_CHART_PROPERTY_INTEGER prop_id, int sub_window = 0);
bool ChartGetInteger(long chart_id, ENUM_CHART_PROPERTY_INTEGER prop_id, int sub_window, long& long_var);

// ChartGetString - 2 overloads
string ChartGetString(long chart_id, ENUM_CHART_PROPERTY_STRING prop_id);
bool ChartGetString(long chart_id, ENUM_CHART_PROPERTY_STRING prop_id, string& string_var);
bool ChartNavigate(long chart_id, ENUM_CHART_POSITION position, int shift = 0);
long ChartID();
int ChartWindowFind(long chart_id, string indicator_shortname);
bool ChartTimePriceToXY(long chart_id, int sub_window, datetime time, double price, int& x, int& y);
bool ChartXYToTimePrice(long chart_id, int x, int y, int& sub_window, datetime& time, double& price);
int ChartWindowOnDropped();
double ChartPriceOnDropped();
datetime ChartTimeOnDropped();
int ChartXOnDropped();
int ChartYOnDropped();
bool ChartSaveTemplate(long chart_id, string filename);
bool ChartApplyTemplate(long chart_id, string filename);
bool ChartScreenShot(long chart_id, string filename, int width, int height, ENUM_ALIGN_MODE align_mode = ALIGN_RIGHT);
int WindowBarsPerChart();
string WindowExpertName();
int WindowFind(string name);
int WindowFirstVisibleBar();
int WindowHandle(string symbol, int timeframe);
bool WindowIsVisible(int index);
int WindowOnDropped();
double WindowPriceMax(int index = 0);
double WindowPriceMin(int index = 0);
double WindowPriceOnDropped();
void WindowRedraw();
bool WindowScreenShot(string filename, int size_x, int size_y, int start_bar = -1, int chart_scale = -1, int chart_mode = -1);
datetime WindowTimeOnDropped();
int WindowsTotal();
int WindowXOnDropped();
int WindowYOnDropped();

// Database functions (SQLite)
// Database flags
#define DATABASE_OPEN_READONLY  1
#define DATABASE_OPEN_READWRITE 2
#define DATABASE_OPEN_CREATE    4
#define DATABASE_OPEN_MEMORY    8
#define DATABASE_OPEN_COMMON    16

// Database field types
enum ENUM_DATABASE_FIELD_TYPE {
    DATABASE_FIELD_TYPE_INVALID=-1,
    DATABASE_FIELD_TYPE_INTEGER=1,
    DATABASE_FIELD_TYPE_FLOAT=2,
    DATABASE_FIELD_TYPE_TEXT=3,
    DATABASE_FIELD_TYPE_BLOB=4,
    DATABASE_FIELD_TYPE_NULL=5
};

int DatabaseOpen(string filename, uint flags);
void DatabaseClose(int database);
bool DatabaseExecute(int database, string sql);
int DatabasePrepare(int database, string sql, ...);
bool DatabaseReset(int request);
bool DatabaseRead(int request);
bool DatabaseReadBind(int request, void& struct_object);
void DatabaseFinalize(int request);
bool DatabaseTransactionBegin(int database);
bool DatabaseTransactionCommit(int database);
bool DatabaseTransactionRollback(int database);
int DatabaseColumnsCount(int request);
string DatabaseColumnName(int request, int column);
ENUM_DATABASE_FIELD_TYPE DatabaseColumnType(int request, int column);
int DatabaseColumnSize(int request, int column);
string DatabaseColumnText(int request, int column);
long DatabaseColumnInteger(int request, int column);
double DatabaseColumnDouble(int request, int column);
bool DatabaseColumnBlob(int request, int column, void& data[]);
bool DatabaseTableExists(int database, string table);
bool DatabaseExport(int database, string table_or_sql, string filename, uint flags, string separator);
bool DatabaseImport(int database, string filename, string table, uint flags, string separator, ulong skip_rows, string skip_comments);
bool DatabasePrint(int database, string table_or_sql, uint flags);

// Indicator functions
int iAC(string symbol, ENUM_TIMEFRAMES period);
int iAD(string symbol, ENUM_TIMEFRAMES period, ENUM_APPLIED_VOLUME applied_volume);
int iADX(string symbol, ENUM_TIMEFRAMES period, int adx_period);
int iADXWilder(string symbol, ENUM_TIMEFRAMES period, int adx_period);
int iAlligator(string symbol, ENUM_TIMEFRAMES period, int jaw_period, int jaw_shift, int teeth_period, int teeth_shift, int lips_period, int lips_shift, ENUM_MA_METHOD ma_method, ENUM_APPLIED_PRICE applied_price);
int iAMA(string symbol, ENUM_TIMEFRAMES period, int ama_period, int fast_ma_period, int slow_ma_period, int ama_shift, ENUM_APPLIED_PRICE applied_price);
int iAO(string symbol, ENUM_TIMEFRAMES period);
int iATR(string symbol, ENUM_TIMEFRAMES period, int ma_period);
int iBearsPower(string symbol, ENUM_TIMEFRAMES period, int ma_period);
int iBullsPower(string symbol, ENUM_TIMEFRAMES period, int ma_period);
int iBands(string symbol, ENUM_TIMEFRAMES period, int bands_period, int bands_shift, double deviation, ENUM_APPLIED_PRICE applied_price);
int iBWMFI(string symbol, ENUM_TIMEFRAMES period, ENUM_APPLIED_VOLUME applied_volume);
int iCCI(string symbol, ENUM_TIMEFRAMES period, int ma_period, ENUM_APPLIED_PRICE applied_price);
int iChaikin(string symbol, ENUM_TIMEFRAMES period, int fast_ma_period, int slow_ma_period, ENUM_MA_METHOD ma_method, ENUM_APPLIED_VOLUME applied_volume);
int iCustom(string symbol, ENUM_TIMEFRAMES period, string name, ...);
int iDEMA(string symbol, ENUM_TIMEFRAMES period, int ma_period, int ma_shift, ENUM_APPLIED_PRICE applied_price);
int iDeMarker(string symbol, ENUM_TIMEFRAMES period, int ma_period);
int iEnvelopes(string symbol, ENUM_TIMEFRAMES period, int ma_period, int ma_shift, ENUM_MA_METHOD ma_method, ENUM_APPLIED_PRICE applied_price, double deviation);
int iForce(string symbol, ENUM_TIMEFRAMES period, int ma_period, ENUM_MA_METHOD ma_method, ENUM_APPLIED_VOLUME applied_volume);
int iFractals(string symbol, ENUM_TIMEFRAMES period);
int iFrAMA(string symbol, ENUM_TIMEFRAMES period, int ma_period, int ma_shift, ENUM_APPLIED_PRICE applied_price);
int iGator(string symbol, ENUM_TIMEFRAMES period, int jaw_period, int jaw_shift, int teeth_period, int teeth_shift, int lips_period, int lips_shift, ENUM_MA_METHOD ma_method, ENUM_APPLIED_PRICE applied_price);
int iIchimoku(string symbol, ENUM_TIMEFRAMES period, int tenkan_sen, int kijun_sen, int senkou_span_b);
int iMA(string symbol, ENUM_TIMEFRAMES period, int ma_period, int ma_shift, ENUM_MA_METHOD ma_method, ENUM_APPLIED_PRICE applied_price);
int iMACD(string symbol, ENUM_TIMEFRAMES period, int fast_ema_period, int slow_ema_period, int signal_period, ENUM_APPLIED_PRICE applied_price);
int iMFI(string symbol, ENUM_TIMEFRAMES period, int ma_period, ENUM_APPLIED_VOLUME applied_volume);
int iMomentum(string symbol, ENUM_TIMEFRAMES period, int mom_period, ENUM_APPLIED_PRICE applied_price);
int iOBV(string symbol, ENUM_TIMEFRAMES period, ENUM_APPLIED_VOLUME applied_volume);
int iOsMA(string symbol, ENUM_TIMEFRAMES period, int fast_ema_period, int slow_ema_period, int signal_period, ENUM_APPLIED_PRICE applied_price);
int iRSI(string symbol, ENUM_TIMEFRAMES period, int ma_period, ENUM_APPLIED_PRICE applied_price);
int iRVI(string symbol, ENUM_TIMEFRAMES period, int ma_period);
int iSAR(string symbol, ENUM_TIMEFRAMES period, double step, double maximum);
int iStdDev(string symbol, ENUM_TIMEFRAMES period, int ma_period, int ma_shift, ENUM_MA_METHOD ma_method, ENUM_APPLIED_PRICE applied_price);
int iStochastic(string symbol, ENUM_TIMEFRAMES period, int Kperiod, int Dperiod, int slowing, ENUM_MA_METHOD ma_method, ENUM_STO_PRICE price_field);
int iTEMA(string symbol, ENUM_TIMEFRAMES period, int ma_period, int ma_shift, ENUM_APPLIED_PRICE applied_price);
int iTriX(string symbol, ENUM_TIMEFRAMES period, int ma_period, ENUM_APPLIED_PRICE applied_price);
int iVIDyA(string symbol, ENUM_TIMEFRAMES period, int cmo_period, int ema_period, int ma_shift, ENUM_APPLIED_PRICE applied_price);
int iVolumes(string symbol, ENUM_TIMEFRAMES period, ENUM_APPLIED_VOLUME applied_volume);
int iWPR(string symbol, ENUM_TIMEFRAMES period, int calc_period);

bool IndicatorSetDouble(int prop_id, double prop_value);
bool IndicatorSetDouble(int prop_id, int prop_modifier, double prop_value);
bool IndicatorSetInteger(int prop_id, int prop_value);
bool IndicatorSetInteger(int prop_id, int prop_modifier, int prop_value);
bool IndicatorSetString(int prop_id, string prop_value);
bool IndicatorSetString(int prop_id, int prop_modifier, string prop_value);
int IndicatorCreate(string symbol, ENUM_TIMEFRAMES period, ENUM_INDICATOR indicator_type, int parameters_cnt = 0, const MqlParam parameters_array[] = 0);
bool IndicatorRelease(int indicator_handle);

// Graphical object plotting
bool PlotIndexSetDouble(int plot_index, int prop_id, double prop_value);
bool PlotIndexSetInteger(int plot_index, int prop_id, int prop_value);
bool PlotIndexSetString(int plot_index, int prop_id, string prop_value);
int PlotIndexGetInteger(int plot_index, int prop_id);
bool SetIndexBuffer(int index, double buffer[], ENUM_INDEXBUFFER_TYPE data_type = INDICATOR_DATA);

// Index buffer enum
enum ENUM_INDEXBUFFER_TYPE { INDICATOR_DATA=0, INDICATOR_COLOR_INDEX=1, INDICATOR_CALCULATIONS=2 };

// Event handling
bool EventSetTimer(int seconds);
bool EventSetMillisecondTimer(int milliseconds);
void EventKillTimer();
bool EventChartCustom(long chart_id, ushort custom_event_id, long lparam, double dparam, string sparam);

// Global variable functions
bool GlobalVariableCheck(string name);
datetime GlobalVariableTime(string name);
bool GlobalVariableDel(string name);
double GlobalVariableGet(string name);
double GlobalVariableGet(string name, double& double_var);
string GlobalVariableName(int index);
bool GlobalVariableSet(string name, double value);
void GlobalVariablesFlush();
bool GlobalVariableTemp(string name);
bool GlobalVariableSetOnCondition(string name, double value, double check_value);
int GlobalVariablesDeleteAll(string prefix_name = 0, datetime limit_data = 0);
int GlobalVariablesTotal();

// Resource functions
bool ResourceCreate(string resource_name, const uint data[], uint img_width, uint img_height, uint data_xoffset, uint data_yoffset, uint data_width, ENUM_COLOR_FORMAT color_format);
bool ResourceCreate(string resource_name, string path);
bool ResourceFree(string resource_name);
bool ResourceReadImage(string resource_name, uint data[], uint& width, uint& height);
bool ResourceSave(string resource_name, string file_name);

enum ENUM_COLOR_FORMAT { COLOR_FORMAT_XRGB_NOALPHA=0, COLOR_FORMAT_ARGB_RAW=1, COLOR_FORMAT_ARGB_NORMALIZE=2 };

// OpenCL functions
int CLHandleType(int handle);
int CLGetInfoInteger(int handle, ENUM_OPENCL_PROPERTY_INTEGER prop);
bool CLContextCreate(int device);
bool CLContextFree(int context);
int CLBufferCreate(int context, uint size, uint flags);
bool CLBufferFree(int buffer);
bool CLBufferWrite(int buffer, const void* data, uint buffer_offset = 0, uint data_offset = 0, uint data_count = 0);
bool CLBufferRead(int buffer, void* data, uint buffer_offset = 0, uint data_offset = 0, uint data_count = 0);

enum ENUM_OPENCL_PROPERTY_INTEGER { CL_PLATFORM_VENDOR=0, CL_DEVICE_TYPE=1, CL_DEVICE_VENDOR_ID=2, CL_DEVICE_MAX_COMPUTE_UNITS=3, CL_DEVICE_MAX_CLOCK_FREQUENCY=4, CL_DEVICE_GLOBAL_MEM_SIZE=5, CL_DEVICE_LOCAL_MEM_SIZE=6, CL_BUFFER_SIZE=7, CL_KERNEL_WORK_GROUP_SIZE=8, CL_KERNEL_LOCAL_MEM_SIZE=9, CL_KERNEL_PRIVATE_MEM_SIZE=10 };

// Cryptography functions
int CryptEncode(ENUM_CRYPT_METHOD method, const uchar data[], const uchar key[], uchar result[]);
int CryptDecode(ENUM_CRYPT_METHOD method, const uchar data[], const uchar key[], uchar result[]);

enum ENUM_CRYPT_METHOD { CRYPT_BASE64=0, CRYPT_AES128=1, CRYPT_AES256=2, CRYPT_DES=3, CRYPT_HASH_SHA1=4, CRYPT_HASH_SHA256=5, CRYPT_HASH_MD5=6, CRYPT_ARCH_ZIP=7 };

// Economic Calendar functions
struct MqlCalendarCountry {
    ulong id;
    string name;
    string code;
    string currency;
    string currency_symbol;
    string url_name;
};

struct MqlCalendarEvent {
    ulong id;
    ENUM_CALENDAR_EVENT_TYPE type;
    ENUM_CALENDAR_EVENT_SECTOR sector;
    ENUM_CALENDAR_EVENT_FREQUENCY frequency;
    ENUM_CALENDAR_EVENT_TIMEMODE time_mode;
    ulong country_id;
    ENUM_CALENDAR_EVENT_UNIT unit;
    ENUM_CALENDAR_EVENT_IMPORTANCE importance;
    ENUM_CALENDAR_EVENT_MULTIPLIER multiplier;
    uint digits;
    string source_url;
    string event_code;
    string name;
};

struct MqlCalendarValue {
    ulong id;
    ulong event_id;
    datetime time;
    datetime period;
    int revision;
    long actual_value;
    long prev_value;
    long revised_prev_value;
    long forecast_value;
    ENUM_CALENDAR_EVENT_IMPACT impact_type;
};

enum ENUM_CALENDAR_EVENT_TYPE {
    CALENDAR_TYPE_EVENT=0, CALENDAR_TYPE_INDICATOR=1, CALENDAR_TYPE_HOLIDAY=2
};
enum ENUM_CALENDAR_EVENT_SECTOR {
    CALENDAR_SECTOR_NONE=0, CALENDAR_SECTOR_MARKET=1, CALENDAR_SECTOR_GDP=2, CALENDAR_SECTOR_JOBS=3,
    CALENDAR_SECTOR_PRICES=4, CALENDAR_SECTOR_MONEY=5, CALENDAR_SECTOR_TRADE=6, CALENDAR_SECTOR_GOVERNMENT=7,
    CALENDAR_SECTOR_BUSINESS=8, CALENDAR_SECTOR_CONSUMER=9, CALENDAR_SECTOR_HOUSING=10,
    CALENDAR_SECTOR_TAXES=11, CALENDAR_SECTOR_HOLIDAYS=12
};
enum ENUM_CALENDAR_EVENT_FREQUENCY {
    CALENDAR_FREQUENCY_NONE=0, CALENDAR_FREQUENCY_WEEK=1, CALENDAR_FREQUENCY_MONTH=2,
    CALENDAR_FREQUENCY_QUARTER=3, CALENDAR_FREQUENCY_YEAR=4, CALENDAR_FREQUENCY_DAY=5
};
enum ENUM_CALENDAR_EVENT_TIMEMODE {
    CALENDAR_TIMEMODE_DATETIME=0, CALENDAR_TIMEMODE_DATE=1, CALENDAR_TIMEMODE_NOTIME=2, CALENDAR_TIMEMODE_TENTATIVE=3
};
enum ENUM_CALENDAR_EVENT_UNIT {
    CALENDAR_UNIT_NONE=0, CALENDAR_UNIT_PERCENT=1, CALENDAR_UNIT_CURRENCY=2, CALENDAR_UNIT_HOUR=3,
    CALENDAR_UNIT_JOB=4, CALENDAR_UNIT_RIG=5, CALENDAR_UNIT_USD=6, CALENDAR_UNIT_PEOPLE=7,
    CALENDAR_UNIT_MORTGAGE=8, CALENDAR_UNIT_VOTE=9, CALENDAR_UNIT_BARREL=10, CALENDAR_UNIT_CUBICFEET=11,
    CALENDAR_UNIT_POSITION=12, CALENDAR_UNIT_BUILDING=13
};
enum ENUM_CALENDAR_EVENT_IMPORTANCE {
    CALENDAR_IMPORTANCE_NONE=0, CALENDAR_IMPORTANCE_LOW=1, CALENDAR_IMPORTANCE_MODERATE=2, CALENDAR_IMPORTANCE_HIGH=3
};
enum ENUM_CALENDAR_EVENT_MULTIPLIER {
    CALENDAR_MULTIPLIER_NONE=0, CALENDAR_MULTIPLIER_THOUSANDS=1, CALENDAR_MULTIPLIER_MILLIONS=2,
    CALENDAR_MULTIPLIER_BILLIONS=3, CALENDAR_MULTIPLIER_TRILLIONS=4
};
enum ENUM_CALENDAR_EVENT_IMPACT {
    CALENDAR_IMPACT_NA=0, CALENDAR_IMPACT_POSITIVE=1, CALENDAR_IMPACT_NEGATIVE=2
};

int CalendarCountries(MqlCalendarCountry countries[]);
bool CalendarCountryById(ulong country_id, MqlCalendarCountry& country);
int CalendarEventByCountry(string country_code, MqlCalendarEvent events[]);
int CalendarEventByCurrency(string currency, MqlCalendarEvent events[]);
bool CalendarEventById(ulong event_id, MqlCalendarEvent& event);
int CalendarValueById(ulong value_id, MqlCalendarValue& value);
int CalendarValueHistory(MqlCalendarValue values[], datetime datetime_from, datetime datetime_to = 0, string country_code = "", string currency = "");
int CalendarValueHistoryByEvent(ulong event_id, MqlCalendarValue values[], datetime datetime_from, datetime datetime_to = 0);
int CalendarValueLast(ulong& change_id, MqlCalendarValue values[], string country_code = "", string currency = "");
int CalendarValueLastByEvent(ulong event_id, ulong& change_id, MqlCalendarValue values[]);

// Network functions
bool SendFTP(string filename, string ftp_path = 0);
bool SendMail(string subject, string some_text);
bool SendNotification(string text);
bool WebRequest(string method, string url, string cookie, string referer, int timeout, const char data[], int data_size, char result[], string& result_headers);
bool WebRequest(string method, string url, string headers, int timeout, const char data[], char result[], string& result_headers);

// Socket functions
int SocketCreate();
bool SocketClose(int socket);
bool SocketConnect(int socket, string server, uint port, uint timeout_receive_ms);
bool SocketIsConnected(int socket);
bool SocketIsReadable(int socket);
bool SocketIsWritable(int socket);
int SocketTimeouts(int socket, uint timeout_send_ms, uint timeout_receive_ms);
int SocketSend(int socket, const uchar buffer[], uint buffer_len);
int SocketTlsSend(int socket, const uchar buffer[], uint buffer_len);
int SocketRead(int socket, uchar buffer[], uint buffer_len, uint timeout_ms);
int SocketTlsRead(int socket, uchar buffer[], uint buffer_len);
bool SocketTlsHandshake(int socket, string host);
int SocketTlsCertificate(int socket, string& subject, string& issuer, string& serial, string& thumbprint, datetime& expiration);
bool SocketTlsReadAvailable(int socket);

// Pointer and object functions
// In MQL5, GetPointer(this) returns the same pointer type, not pointer-to-pointer
template<typename T> T* GetPointer(T* object);  // For GetPointer(this) - returns same type
template<typename T> T* GetPointer(T& object);  // For GetPointer(obj) - returns pointer
template<typename T> void DeletePointer(T* pointer);
int CheckPointer(void* pointer);

// Type checking
template<typename T> bool IsSigned(const T& value);
template<typename T> string typename(const T& value);

// ZeroMemory
template<typename T> void ZeroMemory(T& variable);
template<typename T> void ArrayInitialize(T array[], T value);

//+------------------------------------------------------------------+
//| MQL5 Standard Library Stubs                                      |
//| Trade, Controls, Arrays - auto-generated for clangd              |
//+------------------------------------------------------------------+
#include "mql5_stdlib_stubs.h"

#endif
